Pumpkin-MC/Pumpkin

Cargo.lock, Cargo.toml, pumpkin-world/Cargo.toml, pumpkin/Cargo.toml, pumpkin/src/client/authentication.rs, pumpkin/src/client/client_packet.rs, pumpkin/src/client/mod.rs, pumpkin/src/main.rs, pumpkin/src/server.rs
- Added tokio as a workspace dependancy
- Made main function async
- Removed reqwest blocking feature
- Changed all necessary functions to async (for reqwest)
=> Tokio + reqwest async

Cargo.toml
`codegen-units = 1` increase compile times but it improve both runtime speed and reduce binary size.
`strip = true` strip debug info and symbols from the compiled binary. so it can reduce binary size.
I made simple table for pumpkin binary size and compile times comparison.
| Configuration Option              | Description                                                | Increases Compile Time | Reduces Binary Size   | Improves Runtime Performance | Compile Result (Time; Size)  |
|-----------------------------------|------------------------------------------------------------|-----------------------|-----------------------|------------------------------|--------------------------------------|
| `codegen-units = 1`               | Improves runtime speed and reduces binary size …
=> Add release profile optimiztion

CONTRIBUTING.md, README.md, pumpkin-inventory/src/player.rs, pumpkin-registry/README.md, pumpkin-registry/src/damage_type.rs, pumpkin-registry/src/lib.rs, pumpkin-text/src/click.rs, pumpkin-text/src/lib.rs, pumpkin-text/src/style.rs, pumpkin-world/src/vector3.rs, pumpkin-world/src/world.rs, pumpkin/src/client/mod.rs, pumpkin/src/config/mod.rs, pumpkin/src/config/resource_pack.rs
Not a very interesting change but I noticed some typos while reading the code and decided to go over the project and fix as many as I could.
=> Fix some minor typos

pumpkin/src/commands/cmd_gamemode.rs, pumpkin/src/commands/cmd_help.rs, pumpkin/src/commands/cmd_pumpkin.rs, pumpkin/src/commands/cmd_stop.rs, pumpkin/src/commands/dispatcher.rs, pumpkin/src/commands/mod.rs, pumpkin/src/commands/tree.rs, pumpkin/src/commands/tree_builder.rs, pumpkin/src/commands/tree_format.rs
As discussed in #39 
Current limitations: Help for commands with more than one branch ends after that branch. Vanilla Minecraft does that, too, but also allows displaying help for a specific branch if that branch is specified in the help command, which this pr does not implement.
=> Add prettier CommandTree formatting for help command and usage hint

pumpkin/src/client/player_packet.rs
make sure the players gamemode is creative when client sends SSetCreativeSlot
=> Add permissions check for SSetCreativeSlot

pumpkin/src/client/player_packet.rs, pumpkin/src/server.rs
`broadcast_packet_expect` -> `broadcast_packet_except`
Also added a doc comment.
=> Fix typo in method name

Cargo.lock, pumpkin/Cargo.toml
On nixOS installing pkg-config and the system `openssl` is a bit of a pain so why don't we use `rustls` instead?
I imagine compiling for Windows isn't fun either but not too sure how their system crypto library works.
=> Use rustls instead of system openssl to make compilation easier

pumpkin-inventory/src/player.rs
The correct value was already used in the second match arm.
`slot - 4` goes up to value `4` (`8` - `4`), `self.armor` has 4 elements (max index is `3`)
=> Fix `set_slot` armor indexing (Off-by-one error)

Cargo.lock, pumpkin-protocol/src/client/play/c_chunk_data.rs, pumpkin-world/Cargo.toml, pumpkin-world/src/biome.rs, pumpkin-world/src/block/block_id.rs, pumpkin-world/src/block/block_registry.rs, pumpkin-world/src/block/mod.rs, pumpkin-world/src/chunk.rs, pumpkin-world/src/coordinates.rs, pumpkin-world/src/level.rs, pumpkin-world/src/lib.rs, pumpkin-world/src/radial_chunk_iterator.rs, pumpkin-world/src/world_gen/generator.rs, pumpkin-world/src/world_gen/generic_generator.rs, pumpkin-world/src/world_gen/implementations/mod.rs, pumpkin-world/src/world_gen/implementations/superflat.rs, pumpkin-world/src/world_gen/mod.rs, pumpkin-world/src/world_gen/seed.rs, pumpkin/src/client/player_packet.rs, pumpkin/src/server.rs
This PR adds Superflat Worldgeneration.
By default the vanilla `./world` file is still read but chunks that are not generated yet are replaced by newly generated chunks.
This is currently not configurable because I plan on making it configurable after the "move config to `LazyLock`" PR will be rejected/merged.
If I went a bit overboard with all the refactors tell me and I'll cherry-pick the commits into another branch.
All of the commits compile individually and were checked with
```
cargo clippy -- -W clippy::complexity -W clippy::correctness -W clippy::perf -W clippy::style -W clippy::suspicious
cargo build
cargo check --release
cargo fmt --check
```
related to #36
=> Superflat Worldgeneration

Cargo.lock, pumpkin-core/Cargo.toml, pumpkin-core/src/lib.rs, pumpkin-core/src/random/gaussian.rs, pumpkin-core/src/random/mod.rs, pumpkin-core/src/random/xoroshiro128.rs
A rust implementation of one of Minecraft's RNGs: XOROshiro128, including tests cases against the results of equivalent java code
=> implement xoroshiro128 RNG

Cargo.lock, pumpkin-world/Cargo.toml, pumpkin-world/src/block/block_registry.rs, pumpkin-world/src/global_registry.rs, pumpkin-world/src/item/item_registry.rs
- Increases MSRV
- Removes a dependency (-compiletime)
there's no change in program behavior in this PR.
=> Remove lazy static in favor of LazyLock

pumpkin-protocol/src/bytebuf/deserializer.rs, pumpkin-protocol/src/bytebuf/mod.rs, pumpkin-protocol/src/server/handshake/mod.rs, pumpkin-protocol/src/server/login/s_encryption_response.rs, pumpkin-protocol/src/server/login/s_login_start.rs, pumpkin-protocol/src/server/login/s_plugin_response.rs, pumpkin-protocol/src/server/play/s_chat_message.rs, pumpkin-protocol/src/server/play/s_interact.rs, pumpkin-protocol/src/server/play/s_player_command.rs, pumpkin/src/proxy/velocity.rs
Got this error after leaving the server on a public ip:
```
thread 'main' panicked at /home/minecraft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.7.1/src/bytes_mut.rs:394:9:
split_to out of bounds: 3 <= 2
stack backtrace:
0: rust_begin_unwind
at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
1: core::panicking::panic_fmt
at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
2: bytes::bytes_mut::BytesMut::split_to
at /home/minecraft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.7.1/src/bytes_mut.rs:394:9
3: <bytes::bytes_mut::BytesMut as bytes::buf::buf_impl::Buf>::copy_to_bytes
at /home/minecraft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.7.1/src/bytes_mut.rs:1165:9
4: …
```
=> Incoming Packet Validation

pumpkin-core/src/text/hover.rs, pumpkin-inventory/src/player.rs, pumpkin-protocol/src/client/play/c_login.rs, pumpkin-protocol/src/client/play/c_particle.rs, pumpkin-protocol/src/client/play/c_player_chat_message.rs, pumpkin-protocol/src/client/play/c_spawn_player.rs, pumpkin-protocol/src/packet_encoder.rs, pumpkin-protocol/src/slot.rs, pumpkin-world/src/chunk.rs, pumpkin-world/src/global_registry.rs, pumpkin-world/src/item/item_registry.rs, pumpkin-world/src/level.rs, pumpkin-world/src/world_gen/generator.rs, pumpkin-world/src/world_gen/implementations/superflat.rs, pumpkin-world/src/world_gen/mod.rs, pumpkin-world/src/world_gen/seed.rs, pumpkin/src/client/authentication.rs, pumpkin/src/commands/cmd_gamemode.rs, pumpkin/src/commands/tree.rs, pumpkin/src/commands/tree_builder.rs, pumpkin/src/main.rs
=> Removed unused #[allow()]'s

pumpkin-protocol/src/lib.rs
My public facing server received another error:
```
thread 'main' panicked at /home/minecraft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.7.1/src/lib.rs:138:5:
advance out of bounds: the len is 0 but advancing by 1
stack backtrace:
0: rust_begin_unwind
at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
1: core::panicking::panic_fmt
at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
2: bytes::panic_advance
at /home/minecraft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.7.1/src/lib.rs:138:5
3: bytes::buf::buf_impl::Buf::get_u8
at /home/minecraft/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.7.1/src/buf/buf_impl.rs:304:13
4: pumpkin_protocol::VarInt::decode
at …
```
=> Buffer check for varint decoding

Cargo.toml, pumpkin-plugin/Cargo.toml, pumpkin-plugin/src/api/identifer.rs, pumpkin-plugin/src/lib.rs, pumpkin/Cargo.toml
- Made a `plugins` feature in `pumpkin-plugin`
- Made a `plugins` feature in `pumpkin`, which enables the `plugins` feature in `pumpkin-plugin`
- Made the feature default
To run the project without plugins, use `cargo run --no-default-features`
=> Make a way to disable extism

pumpkin-inventory/src/open_container.rs, pumpkin/src/client/authentication.rs, pumpkin/src/client/client_packet.rs, pumpkin/src/client/container.rs, pumpkin/src/client/mod.rs, pumpkin/src/client/player_packet.rs, pumpkin/src/commands/cmd_echest.rs, pumpkin/src/commands/dispatcher.rs, pumpkin/src/commands/mod.rs, pumpkin/src/commands/tree.rs, pumpkin/src/commands/tree_builder.rs, pumpkin/src/entity/player.rs, pumpkin/src/main.rs, pumpkin/src/rcon/mod.rs, pumpkin/src/server/mod.rs
This cleanup's goal is to make all `Server` functions only require &self. This means that `Server` can now be a `Arc<Server>` instead of `Arc<Mutex<Server>>`, which solves a lot of deadlock problems.
=> Cleanup Server struct

Cargo.lock, Cargo.toml, pumpkin-core/src/math/position.rs, pumpkin-core/src/math/vector3.rs, pumpkin-inventory/Cargo.toml, pumpkin-inventory/src/drag_handler.rs, pumpkin-inventory/src/lib.rs, pumpkin-inventory/src/open_container.rs, pumpkin-inventory/src/player.rs, pumpkin-protocol/src/lib.rs, pumpkin-world/Cargo.toml, pumpkin-world/src/level.rs, pumpkin/Cargo.toml, pumpkin/src/client/client_packet.rs, pumpkin/src/client/container.rs, pumpkin/src/client/mod.rs, pumpkin/src/client/player_packet.rs, pumpkin/src/commands/cmd_echest.rs, pumpkin/src/commands/cmd_gamemode.rs, pumpkin/src/entity/mod.rs, pumpkin/src/entity/player.rs, pumpkin/src/main.rs, pumpkin/src/proxy/velocity.rs, pumpkin/src/server/mod.rs, pumpkin/src/world/mod.rs, pumpkin/src/world/player_chunker.rs
> [!WARNING]
> This pull request requires review as it has a high likelihood of introducing a bug and should be thoroughly examined before approval.
This PR includes the following changes:
- Added `parking_lot` and `crossbeam` dependencies.
- Replaced all `std::sync::Mutex` by `parking_lot::Mutex` and refactored implementation accordingly.
- Replaced all `Mutex<T> where T: Copy` by `crossbeam::AtomicCell<T>` and refactored implementation accordingly.
Significant portions of the code involve setting Mutex on frequently updated fields and certain types that implement Copy. This optimization is expected to reduce locking overhead and improve overall performance.
- Types that do not implement `Copy` are now wrapper into `parking_lot::Mutex` and the overall `.unwrap()` or `expect()` around …
=> Improved synchronization primitives

Dockerfile, README.md
The port of the Pumpkin server needs to be exposed to be accessable from the docker container
=> expose docker container port

pumpkin/src/main.rs
This PR exits the program (to kill the tokio runtime) if the main thread panics rather than have the program hang in limbo while the tokio runtime continues.
=> kill the program if the main thread panics

docs/developer/authentication.md
This very small PR updates the Wikipedia link in the Authentication docs page from German to English.
Changes:
- Updated the link for the "Denial of Service" (DoS) article from de.wikipedia.org to en.wikipedia.org
=> docs: update Wikipedia link from German to English version

Dockerfile
Make dockerfile uses cargo cache to go from 2m30s to 0s if nothing changes or 40 secondes if there is a change is the rust code to compile
=> feat : make dockerfile uses cargo cache

pumpkin-core/src/math/mod.rs, pumpkin-core/src/random/gaussian.rs, pumpkin-core/src/random/mod.rs, pumpkin-world/src/world_gen/generic_generator.rs, pumpkin-world/src/world_gen/noise/density/end.rs, pumpkin-world/src/world_gen/noise/density/noise.rs, pumpkin-world/src/world_gen/noise/density/spline.rs, pumpkin-world/src/world_gen/noise/density/terrain_helpers.rs, pumpkin-world/src/world_gen/noise/mod.rs, pumpkin-world/src/world_gen/noise/perlin.rs, pumpkin-world/src/world_gen/noise/simplex.rs
This uses Rust standard library's`mul_add`, which is more accurate and performs more efficiently than the equivalent `(a * b) + c`. Also see [the standard library docs](https://doc.rust-lang.org/stable/std/primitive.f64.html#method.mul_add) for more info.
=> Optimize floating point operations

docs/about/benchmarks.md
This PR makes it clearer that minestom is built with Java, while the benchmarks are run with Kotlin
=> Correct language used by minestom to Java

pumpkin-core/src/math/mod.rs, pumpkin-core/src/random/gaussian.rs, pumpkin-core/src/random/mod.rs, pumpkin-world/src/world_gen/generic_generator.rs, pumpkin-world/src/world_gen/noise/density/end.rs, pumpkin-world/src/world_gen/noise/density/noise.rs, pumpkin-world/src/world_gen/noise/density/spline.rs, pumpkin-world/src/world_gen/noise/density/terrain_helpers.rs, pumpkin-world/src/world_gen/noise/mod.rs, pumpkin-world/src/world_gen/noise/perlin.rs, pumpkin-world/src/world_gen/noise/simplex.rs
This uses mul_add in some cases, but maintains parity with Java and passes the unit tests.
=> Optimize some floating point operations, but maintain parity with Java

docs/.vitepress/components/FmtDateTime.vue, docs/.vitepress/components/FmtNum.vue, docs/.vitepress/theme/index.ts, docs/about/benchmarks.md
This PR formats dates and numbers to be formatted for each locale correctly. This also converts times to the user's respective time zone.
This introduces 2 new Vue components, FmtNum and FmtDateTime. These can be used as normal Vue components in the markdown files.
Everything is adjusted based on region, using the Intl JavaScript apis. ***To be clear, there is no actual translation. Only the numbers and dates are formatted as per the user region.***
Also, there are improvements to the benchmarking page so that it flows more smoothly.
=> Format numbers and dates per region

pumpkin/src/client/mod.rs
Hi!
In pumpkin\src\client\mod.rs if an error occur in the poll function the server crash:
With the fix (match instead of using unwrap) the server don't panic.
=> Prevent panic on client poll function

pumpkin-world/Cargo.toml, pumpkin-world/src/cylindrical_chunk_iterator.rs, pumpkin-world/src/level.rs, pumpkin/src/client/mod.rs, pumpkin/src/entity/player.rs, pumpkin/src/world/mod.rs, pumpkin/src/world/player_chunker.rs
If the chunk fetcher spawns and calls level.fetch_chunks and the chunk sender has not spawned yet, because the function is synchronous, the channel can be filled with no consumer
=> Fix chunk loading deadlock and dangling chunk memory

pumpkin/src/client/client_packet.rs
Fixed a typo in client_packets.rs.
I believe all references to the function (1 of them - on line 155) have been renamed to reflect the corrected spelling.
I ran and joined the server with no problems after making this change.
Thought I'd start out with a super basic pull request just to make sure I'm on the right track with contributing to the project. Cheers 🙂
=> fix: autenticate -> authenticate

pumpkin/src/client/authentication.rs, pumpkin/src/client/client_packet.rs, pumpkin/src/commands/arg_player.rs, pumpkin/src/server/mod.rs, pumpkin/src/world/mod.rs
This PR aims to resolve the to-do item [Check if player already joined][1].
This is implemented via two checks:
1. **Prevent duplicate UUIDs.**
Stops a player from logging in to the server if they are already playing (or if their UUID is being used in some other narrow possibility).
3. **Prevent duplicate usernames.**
Stops a player from taking the same username as an online player.
Of course, this is primarily made for offline-mode servers. However, it *might* be possible that this serves as a protection for online-mode servers, in case someone does a name change whilst connected, someone takes their old name, and tries to connect.
Please note, I'm a Rust newbie, so please check my code thoroughly for any mistakes. 🙂 
[1]: https://github.com/users/Snowiiii/projects/12/views/3?pane=issue&i …
=> Prevent duplicate profiles

Cargo.toml, pumpkin-protocol/src/lib.rs, pumpkin-world/src/level.rs, pumpkin/Cargo.toml, pumpkin/src/client/mod.rs, pumpkin/src/entity/player.rs, pumpkin/src/main.rs, pumpkin/src/world/mod.rs, pumpkin/src/world/player_chunker.rs
This PR handles two edge cases that can leave chunks in memory:
1) A client disconnected before all chunks are sent
2) A client moving so fast that a chunk that was in render distance is no longer in render distance before the chunk packet is sent
~~A future implementation would somehow cancel the work being done to generate chunks if they are no longer needed.~~
=> Handle chunks in an intermediary state

pumpkin/src/world/mod.rs
These functions access only the world itself's current players, and thus the old documentation was incorrect saying that it accesses the server's online players.
=> world docs: corrected to 'world', not 'server'

docker-compose.yml
This resolves #174.
I've chosen to make this compose file purely for development use (and thus sticks with `build: .`, rather than using an image).
Instead, for server owners, we should provide an example `docker-compose.yml` for them to use which references a public image instead.
This way, both use cases for the compose files are separated.
***
=> docker: add compose file for development

pumpkin/src/entity/player.rs, pumpkin/src/server/mod.rs, pumpkin/src/world/mod.rs
This implementation will send a 'joined the game' and 'left the game' message akin to the vanilla server when a player joins or disconnects respectively.
One caveat with this implementation is that it only broadcasts the join/quit messages to players in the same world, unlike the vanilla server, which broadcasts it to all online players (regardless of their world).
I discussed this with Alex who suggested to keep it as per-world (seemingly for now?) - [Discord conversation](https://discord.com/channels/1268592337445978193/1268611318617866261/1299668206734147597).
Regardless, this implementation works perfectly on my end. (yes, it has been tested)
Resolves #188 
Screenshot:
=> Add player join and quit messages.

pumpkin-config/src/lib.rs, pumpkin/src/client/client_packet.rs, pumpkin/src/server/mod.rs
Resolves #189 
Ready for review
TBD in future: allow operators to bypass full server. need to wait for operator/permission stuff to be implemented first.
=> Implement max player limit

Cargo.toml, pumpkin/Cargo.toml, pumpkin/src/main.rs
This PR enables the `termination` feature in `ctrlc` so that `sigterm` and `sighup` are also handled on UNIX systems. This in turn improves Docker compatibility since containers now listen to the `SIGTERM` signal it sends to containers when trying to stop the container via `Ctrl-C` whilst attached.
Resolves #182; please check this issue for more information.
***
=> Implement cross platform signal handling with `tokio`

docs/.vitepress/config.mts, docs/developer/contributing.md
A Detailed Description:
Instead of linking to CONTRIBUTING.md, there is now a page build for the website with a bit more information.
A description of the tests performed to verify the changes:
npm install   |   npm run docs:build   |   npm run docs:preview
=> Added detailed documentation on how to contribute

pumpkin/src/world/scoreboard.rs
A Detailed Description:
when I was reading the code I accidentally came across this:
```rust
impl Default for Scoreboard {
fn default() -> Self {
Self::new()
}
}
```
In my opinion, this is a useless piece of code, because we can use #[derive(Default)] instead of this, for speed up
code read time.
`cargo run` and joining to server
=> use derive macro for Default trait on Scoreboard struct

Cargo.toml, pumpkin-protocol/src/client/play/c_chunk_data.rs
- Replaced the HashMap in CChunkData::write with a Vec
- Added profiling profile
Even though Vec has a worse time complexity for this, the HashMap overhead is worse for performance
Performance profiling was done using cargo-flamegraph.
If this breaks something I'll be genuinely surprised.
=> small CChunkData write improvement

pumpkin-protocol/src/server/play/s_set_held_item.rs
*
A Detailed Description:  According to the wiki we need to use (~~0x2F~~) 0x31 for set held item, this fixes the bug where if you have something in your 1st slot you would be able to place it with any other slot selected. 
This issue is partly referenced in #230
A description of the tests performed to verify the changes: Put a block in the first slot, select said slot, then change the selected slot to any other, then try placing the block
=> Fix: Use correct packet for set_help_item

pumpkin/src/command/commands/cmd_list.rs, pumpkin/src/command/commands/cmd_stop.rs, pumpkin/src/command/commands/mod.rs, pumpkin/src/command/mod.rs
- Added command /list that print the names of online players
- Kicking players with a proper message on /stop (Maybe should be added on signal interrupt)
Use /list in game or in console with or without online players
Use /stop and see the message
N/A
=> List command + Better message on server stop

pumpkin/src/world/mod.rs, pumpkin/src/world/player_chunker.rs
Fix: https://github.com/Snowiiii/Pumpkin/issues/229
Fix: Reported in Discord
```
mini-1   | thread 'tokio-runtime-worker' panicked at pumpkin/src/world/mod.rs:592:33:
mini-1   | mpsc bounded channel requires buffer > 0
mini-1   | stack backtrace:
mini-1   |    0:     0x55f9d5e191ac - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h304520fd6a30aa07
mini-1   |    1:     0x55f9d5b96c6b - core::fmt::write::hf5713710ce10ff22
mini-1   |    2:     0x55f9d5deca72 - std::io::Write::write_fmt::hda708db57927dacf
mini-1   |    3:     0x55f9d5e1e348 - std::panicking::default_hook::{{closure}}::he1ad87607d0c11c5
mini-1   |    4:     0x55f9d5e1dfd1 - std::panicking::default_hook::h81c8cd2e7c59ee33
mini-1   |    5:     0x55f9d5b7edae - …
```
=> MPSC channel buffer fix

pumpkin-core/src/math/boundingbox.rs, pumpkin/src/client/player_packet.rs, pumpkin/src/entity/mod.rs, pumpkin/src/entity/player.rs, pumpkin/src/world/mod.rs
Added bounding boxes to every Entity, where a block has a width: 1.0 and a height: 1.0. A player has a width: 0.6 and a height: 1.8.
When placing a block, pumpkin now creates a temporary bounding box from that target position and checks whether the player's box collides with it or not. This way player are not able to place blocks in themself.
Tried placing blocks under myself and beside myself.
- Check collision with bounding box of air block and other entities standing in that block, not only with player's own [ ]
=> Check collision before block place

pumpkin/src/client/player_packet.rs
This will disallow any illegal characters in chat.
It functions exactly the same as in the vanilla minecraft server, see net.minecraft.server.PlayerConnectiona(PacketPlayInChat packetplayinchat) net.minecraft.server.SharedConstants.isAllowedChatCharacter(char c0).
I tested by running "MinecraftClient.getInstance().player.networkHandler.sendChatMessage" on the client with ANSI escape codes, disallowed Unicode and '§'.
=> Disallow illegal characters in chat

pumpkin/src/world/mod.rs
- In Survival, press space bar 2 times and you should be falling / jumping.
- In Creative, press space bar 2 times and you should be flying.
=> fix(player/abilities): only set `allow_flying` on Creative mode

Dockerfile, docker-compose.yml
While trying to deploy Pumpkin through Docker I noticed that it's impossible to do so without having the pre-generated `configuration.toml` and `features.toml` files.
The current docker configuration mounts these files into the docker container, which is possible and as long as person that's deploying keeps this in mind they can prepare for this by doing the following:
```bash
touch configuration.toml
touch features.toml
```
This process creates the two files required to bind into the container, however the problem that I found out later on was that Pumpkin does not populate these files when they're empty. Meaning that someone who doesn't look into the source code and the lack of documentation is unable to modify any of the settings without relying on someone else to generate these files …
=> fix(Docker): improve build and compose files

pumpkin/src/client/player_packet.rs
This doesn't need a description... the 4 line (5 if you count the extra one that the formatter added) diff explains it all.
```rs
if victim.living_entity.health.load() <= 0.0 {
// you can trigger this from a non-modded / innocent client client,
// so we shouldn't kick the player
return;
}
```
Hit a dead player (e.g. another player, for testing this, you would usually just open another client and hit that client's player) and see if any damage occurs (it doesn't).
=> fix(combat): kick players attacking dead players (health <= 0.0)

pumpkin-core/src/text/README.md, pumpkin-core/src/text/color.rs, pumpkin-core/src/text/hover.rs, pumpkin-core/src/text/mod.rs, pumpkin-core/src/text/style.rs
Add RGB support to TextComponent
Fix click_event, hover_event, hover ShowText
used TextComponent with click_event(coppy) and hover_event(show) in console and client
=> Add RGB support to TextComponent, Fix some style

pumpkin/src/entity/player.rs
Add one to the y coordinate of the respawn position so players spawn on top of the top block rather than iside of it.
- use /kill
- observe not being inside of a block
=> fix respawn position being inside top block

assets/packets.json, extractor/src/main/kotlin/de/snowii/extractor/extractors/Packets.kt, pumpkin-macros/src/lib.rs, pumpkin-macros/src/packet.rs
Previously in `packets.json`, `clientbound` packets where called `serverbound`, vice versa.
For example the `Login (Play)` packet was in `serverbound` when it's actually sent by the server to the client
Joining the server works as before
=> Fix packet side in extractor

pumpkin/src/entity/player.rs
The issue has been fixed by broadcasting the entity metadata packet with the skin parts inside the respawn function 
I tested it and it works completly fine after this changes 
=> Fixed the issue where the player's second skin layer did not appear after respawn (issue #284).

.gitignore
Should be fairly clear, with the recent changes made in #255 the docker-compose.yml will bind mount `data/` to `/pumpkin`.
When spinning up pumpkin with `docker compose up --build` none of the new files created under `data/` will be in `git status`.
=> git: ignore compose `data/` folder

pumpkin/Cargo.toml, pumpkin/src/main.rs
sysinfo is actively developed, supports android and will default no null values if the OS is not detected.
(See https://github.com/Snowiiii/Pumpkin/issues/311#issuecomment-2483096761)
Ran on Win11 and linux (wls docker) and android (Samsung tabled)
Windows
Android
Docker
=> Use sysinfo, this will fix #311

pumpkin/Cargo.toml, pumpkin/build.rs
tauri-winres is way faster because it is using embed_resource and this also means it does not rely on rc.exe or windres.exe and ar.exe, making cross-compile possible.
(See https://github.com/Snowiiii/Pumpkin/issues/312#issuecomment-2483389125)
=> Use tauri-winres

pumpkin-world/src/block/block_registry.rs
Multiple functions in `block_registry` would do a brute force search by iterating through all blocks until it found a match. This PR would add multiple hashmaps to improve lookup times and improve performance
- Tested world generation, setblock command, block placing and destroying
- Compared memory usage before and after changes on windows, added `~3.2MB` of memory usage
=> Replace Bruteforce search with Hashmap lookup in block_registry

pumpkin-registry/Cargo.toml, pumpkin-registry/src/lib.rs, pumpkin/src/client/player_packet.rs, pumpkin/src/entity/living.rs, pumpkin/src/entity/player.rs, pumpkin/src/main.rs, pumpkin/src/server/mod.rs, pumpkin/src/world/mod.rs
- Now using IndexMap instead of HashMap for registry values so they have consistent ordering between runtime.
- `player.world()` can now be used instead of `&player.living_entity.entity.world`.
- Moved `player.respawn()` to `world.respawn_player()` as `spawn_player` is on world. (might reconsider)
- Preperations for multi-world support where the registry is involved.
- same biome every time
- no spawning in the ground
- multiple players work as before
=> Consistent registry values and player changes

pumpkin-config/src/auth.rs, pumpkin/src/client/authentication.rs
Currently the auth URLs are not optional in features.toml. However, 99% of users will not change these values in the config file. This PR makes these URLs optional in the config file and falls back to the default auth URLs when not specified. By making them optional, they will be supported config options but not required in the config.
While making the URLs optional, I realized that there was a small issue in the code where the auth URL is still used even when `prevent-proxy-connections` is enabled. I fixed that and also fixed the IP address not being added to the URL correctly.
Tested with building and joining the server 👍 
=> Make auth urls optional, fix issues in prevent proxy connections

pumpkin/src/client/player_packet.rs
Fixed typo. 
```BlockOutOfWold``` > ```BlockOutOfWorld```
=> chore(player_packet): fixed typo

pumpkin-protocol/Cargo.toml, pumpkin-protocol/src/packet_decoder.rs, pumpkin-protocol/src/packet_encoder.rs
This merge request change the lib flate2 used to (de)compress packet to using directly [libdeflater](https://github.com/adamkewley/libdeflater) which is a Rust binding of the C heavily optimized libdeflate
Some change have been made:
- first we only create one instance of Decompressor and Compressor since the new constructor can be heavily to be created at each packet encoding / decoding.
- added validation on decompression to ensure the decompressed_size is at the good size, this will avoid some CPU attack when the zlib encoding is wrong
Some benchmark directly from the lib
https://github.com/adamkewley/libdeflater?tab=readme-ov-file#benchmarks
I have created unit test based on previous system with flate2, run them with the new system to ensure we got the same result
And just launched …
=> feat(protocol): Switch from using flate2 to libdeflater to (de)compress zlib

Cargo.toml, pumpkin-core/src/math/vector2.rs, pumpkin-world/src/cylindrical_chunk_iterator.rs, pumpkin/src/entity/player.rs, pumpkin/src/world/player_chunker.rs
- Fixes multiplication overflow with 16+ view distance
- Fixes #253
=> Chunkloading fixes

pumpkin-core/src/text/mod.rs, pumpkin-nbt/src/serializer.rs
This PR contains 2 main changes:
When serializing a sequence to NBT, it is necessary to add a header containing the type of the elements and the length of the sequence. While the `serialize_seq` method sets the state to `FirstListElement`, this state is never parsed when the elements are maps (this issue could possibly exist even for other element types, however I havent been able to test this). In this change I have modified the `serialize_map` function to handle the cases where the state is either a `FirstListElement` or a `ListElement`.
```diff
fn serialize_map(self, _len: Option<usize>) -> Result<Self::SerializeMap> {
+   if let State::FirstListElement { .. } = self.state {
+       self.parse_state(COMPOUND_ID)?;
+   } else if let State::ListElement = self.state {
+       return …
```
=> Text component children + fix nbt serialization for sequences of maps

pumpkin-inventory/src/lib.rs, pumpkin/src/client/combat.rs, pumpkin/src/client/container.rs, pumpkin/src/client/player_packet.rs, pumpkin/src/command/commands/cmd_clear.rs, pumpkin/src/entity/living.rs, pumpkin/src/entity/player.rs
Basically, we need a way to access inventory on entities (player, donkeys, llamas), and this PR refactors the code so that this is possible
I have gone through and tested that the basic inventory functions on player still works
=> Move container to `LivingEntity`

docs/.vitepress/theme/style.css
It was hard to distinguish tips from warnings
befor:
now:
=> Make tip blue

pumpkin-protocol/src/packet_decoder.rs, pumpkin/src/client/mod.rs
This MR fix https://github.com/Snowiiii/Pumpkin/issues/354 by returning in client poll function to avoid reserving 4096 bytes for each wrong packet
Using the small program provided in https://github.com/Snowiiii/Pumpkin/issues/354 and see that ram never went up
=> fix(protocol): Don't reserve memory on packet decoding error

pumpkin-protocol/src/client/play/c_entity_animation.rs, pumpkin/src/client/mod.rs, pumpkin/src/client/player_packet.rs, pumpkin/src/entity/mod.rs, pumpkin/src/entity/player.rs, pumpkin/src/world/mod.rs
* Fixes #361 
* Fixed sneaking not working
* Sneaking in-front of other players work.
* Switching between left and right handed is shown on the client.
* Hit animation swings with right arm for both self and others.
=> Lefthand and sneaking fixes

docs/config/authentication.md, docs/config/commands.md, docs/config/compression.md, docs/config/introduction.md, docs/config/lan-broadcast.md, docs/config/logging.md, docs/config/proxy.md, docs/config/pvp.md, docs/config/query.md, docs/config/rcon.md, docs/config/resource-pack.md
Mostly just corrected a few minor spelling mistakes in some of the configuration pages on the docs, with an occasional word change or addition for better flow of the overall sentence.
=> Fix Minor Spelling Errors

pumpkin/src/entity/player.rs
Set propper gamemode abilities, resolves #367
Tired out with /kill, still able to flying
=> Set propper gamemode abilities, resolves #367

pumpkin-world/src/level.rs, pumpkin/src/entity/player.rs, pumpkin/src/main.rs, pumpkin/src/server/mod.rs, pumpkin/src/world/mod.rs, pumpkin/src/world/player_chunker.rs
This PR fixes the "but no one was watching spam", removes the need to wait for chunks when removing a player and removes the concept of pending tasks from the player, adds perma-loaded spawn chunks, drastically speeds up loading screen time when joining, and leverages rayon rather than async to stream chunks.
Joined a world
=> Fix chunk loading

CONTRIBUTING.md, pumpkin-world/src/cylindrical_chunk_iterator.rs, pumpkin-world/src/level.rs, pumpkin/src/client/container.rs, pumpkin/src/main.rs
https://github.com/Snowiiii/Pumpkin/commit/cd6ac147ec49e47bd3722680511dc55c26b397b0 introduced a regression where CPU intensive tasks are not performed by all CPUs. This is because the rayon pool does not queue tasks until the current task is complete and because the tokio runtime never ends we effectively lose a CPU.
Additionally, the root cause of the tokio runtime choking is because we were waiting for the results of the rayon pool directly from the tokio runtime, blocking it, which obviously defeats the purpose. 
This PR fixes these issues, sorts initial spawn chunks so that rayon processes them in rings rather than slices, and adds a note in CONTRIBUTING.md on how to avoid issues like this in the future.
Joined the server in debug mode and ran commands while chunks loaded
Things need …
=> Use all cpus for intensive tasks

pumpkin-world/src/cylindrical_chunk_iterator.rs, pumpkin-world/src/level.rs, pumpkin/src/world/mod.rs, pumpkin/src/world/player_chunker.rs
To find different chunks we would iterate over the entire rectangular area the chunks covered. This fixes that. 
Fixes https://github.com/Snowiiii/Pumpkin/issues/379 and some edges cases where chunks are not removed from memory
Teleported far out and did not time out
=> Stablize cylindrical chunks

pumpkin-world/src/item/item_registry.rs, pumpkin/src/entity/player.rs
Added basic attack modifiers for all items (ex. swords, axes, maces):
- base_attack_damage - modifies the base attack damage
- base_attack_speed - modifies the attack speed and resulting damage mid way
Tested in offline mode
Counted health damage and compared to wiki
TODO:
- There may be calculated values which are incorrect. I read that MC goes 2 decimal places while Pumpkin uses f32.
- Each hit requires the comparison of many strings. This could be improved by parsing the strings at compile time into enums. 
=> Added Basic Attack Modifiers

pumpkin/src/command/dispatcher.rs
Fixes the issue where the command tree only worked with a single command path.
(👇`/time add` is working. but `/time set` and `/time query` is not working)
All of `/time add`, `/time set`, and `/time query` work.
=> Fix command dispatcher

pumpkin-core/src/random/mod.rs, pumpkin-world/src/level.rs, pumpkin-world/src/world_gen/implementation/test.rs, pumpkin-world/src/world_gen/seed.rs
This PR implements parsing a seed from a string the same as Java.
N/A
=> Parse seeds same as java

.gitignore, pumpkin/src/command/commands/cmd_pumpkin.rs
Add a text that says Github Repository and if you click it opens the github,
https://snowiiii.github.io/Pumpkin/
https://github.com/user-attachments/assets/60d6400b-e1d5-4f0d-bf9b-1882571729c2
- [?] I added new unit tests, so other people don't accidentally break my code by changing other parts of the codebase. [How?](https://doc.rust-lang.org/book/ch11-01-writing-tests.html)
=> Github link in /pumpkin command

pumpkin/src/client/client_packet.rs, pumpkin/src/client/player_packet.rs, pumpkin/src/entity/player.rs, pumpkin/src/world/mod.rs, pumpkin/src/world/player_chunker.rs
This PR properly updates watched chunks on respawn and render distance updates. It also validates the render distance sent, kicking the player if it is negative.
Joined a world and:
- updated render distances
- died and respawned
then validated chunks would load/unload and leave the cache properly.
=> Properly check chunks on respawn, render distance update, and validate render distance

pumpkin/src/command/commands/cmd_seed.rs
Prints the seed as a i64 instead of a u64
Ran /seed with a negative seed
=> Fix seed command output

pumpkin-config/src/lib.rs
Creates configuration files in a separate folder which then can be in a read-only mode.
Addresses https://github.com/Snowiiii/Pumpkin/issues/377
=> Create configs in a folder

pumpkin-inventory/src/drag_handler.rs
Please work
Also, commit made on mobile using Built-in GitHub editor 🔥
Fixes #386
=> fix(pumpkin-inventory/src/drag_handler.rs): divide by 0

pumpkin/src/command/args/arg_command.rs, pumpkin/src/command/args/mod.rs, pumpkin/src/command/client_cmd_suggestions.rs, pumpkin/src/command/commands/cmd_help.rs, pumpkin/src/command/dispatcher.rs, pumpkin/src/command/mod.rs, pumpkin/src/command/tree.rs, pumpkin/src/main.rs, pumpkin/src/net/packet/play.rs, pumpkin/src/net/rcon/mod.rs, pumpkin/src/server/mod.rs, pumpkin/src/world/mod.rs
Makes the command dispatcher mutable via tokio RWLock as a part of the Server struct
There is also a massive over usage of lifetimes in the command codebase that makes it overly constraining. This will not be addressed in this PR.
Opened the console and ran commands
=> make command dispatcher mutable

README.md
Changed the links in the README.md to link to the actual Pumpkin Website url (`https://snowiiii.github.io/Pumpkin/` -> `https://snowiiii.github.io/Pumpkin-Website/`)
Click the links and they dont lead to a 404 page.
=> Fixed Pumpkin website links

pumpkin-config/src/commands.rs, pumpkin/src/entity/player.rs
Added default op level so server admins can set it for test servers.
Add `default_op_level=3` under `commands` section in `features.toml`
Can now do everything except stop server!
=> Added default op level

pumpkin/src/command/client_cmd_suggestions.rs, pumpkin/src/command/commands/cmd_fill.rs, pumpkin/src/command/commands/cmd_gamemode.rs, pumpkin/src/command/commands/cmd_give.rs, pumpkin/src/command/commands/cmd_op.rs, pumpkin/src/command/commands/cmd_say.rs, pumpkin/src/command/commands/cmd_seed.rs, pumpkin/src/command/commands/cmd_setblock.rs, pumpkin/src/command/commands/cmd_stop.rs, pumpkin/src/command/commands/cmd_teleport.rs, pumpkin/src/command/commands/cmd_time.rs, pumpkin/src/command/commands/cmd_transfer.rs, pumpkin/src/command/dispatcher.rs, pumpkin/src/command/mod.rs, pumpkin/src/command/tree_builder.rs
This PR introduced the following:
- When registering a new command, one must specify the permission level
- If a player tries to execute a command without having permission, it will show that to the player
- When a player wants to autocomplete a command without having permission, it will not show in the autocomplete
Closes https://github.com/Pumpkin-MC/Pumpkin/issues/424
=> fix: command permission handling

pumpkin/src/command/args/arg_textcomponent.rs, pumpkin/src/command/args/mod.rs, pumpkin/src/command/commands/cmd_bossbar.rs, pumpkin/src/world/bossbar.rs, pumpkin/src/world/custom_bossbar.rs
This PR migrates from the String implementation to the Vanilla TextComponent
Open up the game and use `/bossbar add minecraft:test {"text":"Pumpkin","color":"gold"}`
Use `/bossbar set minecraft:test players @a`
You should now see the colored bossbar
=> Changed bossbar title to TextComponent instead of String

pumpkin/src/main.rs
Per the logger documentation:
> Enables the user to choose log level by setting RUST_LOG=<level> environment variable. This will use the default level set by with_level if RUST_LOG is not set or can't be parsed as a standard log level.
> This must be called after with_level. If called before with_level, it will have no effect.
Personally, I feel that using a config file, which defaults to *false* to configure whether or not to listen to the environment for enabling and disabling logging is a bit dumb. Usually environment variables are meant to allow you to modify the configuration of a program for one "environment", not necessarily permanently. Especially when you get more complicated environment filtering.
For me, I'm content with `Info` or even `Debug` as the default, but will …
=> fix listening to `RUST_LOG`

pumpkin/src/world/mod.rs
Made the player name and the parameter lower case when matching them. This way, things like player arguments in commands don't need to be case-sensitive. Overall a revolutionary change.
=> Made getting players by name case-insensitive

pumpkin-core/src/math/vector3.rs, pumpkin/src/entity/ai/goal/mod.rs, pumpkin/src/entity/ai/goal/target_goal.rs, pumpkin/src/entity/ai/mod.rs, pumpkin/src/entity/ai/path/mod.rs, pumpkin/src/entity/mob/mod.rs, pumpkin/src/entity/mob/zombie.rs, pumpkin/src/entity/mod.rs, pumpkin/src/server/mod.rs
Add Entity path finding, Make it a goal so we can reuse it for every entity :D
=> Add Path finding

pumpkin-config/src/lib.rs
The word "probably" was mispronounced in a couple of places in the codebase, and I fixed them.
The logic of the code is unchanged, only a typo was fixed.
=> Fix misspelled word "probably"

pumpkin/src/entity/player.rs, pumpkin/src/main.rs, pumpkin/src/net/packet/play.rs, pumpkin/src/net/rcon/mod.rs
Whenever the fill command is run with a large selection, the client times out. This is because the packet processing is halted because it is processing the command. The best way to solve this would be to process the command in a new task so that packet processing in not halted for commands that take longer to run. This should stop the client from timing out when they run a command that has longer run time and if they do time out while a command is running for whatever reason, the client will properly be removed from the server.
Forcibly cause a timeout (by an extremely large selection with the fill command), and make sure that the player can rejoin the server.
=> Fix players timing out after a command executes for a while

pumpkin-util/src/text/mod.rs, pumpkin/src/net/packet/play.rs
Added restrictions and errors for when a player tries to place blocks above or below the world or while in the wrong gamemode.
Note: In order to send the maximum height message, it was necessary to modify the type of the variable “with” of TextComponent::Translate, because it crashes the client.
(Theory: The client crashes due to a circular encoding of the “with” value).
=> Placement restrictions

pumpkin-util/src/math/boundingbox.rs, pumpkin-world/src/block/block_registry.rs, pumpkin/src/net/packet/play.rs
Changed the system of detection of intersection of the player with the placed blocks so that it respects the collision of the block.
This should fix the issues #267 and #353.
Note: Since the blocks are not yet placed with the right state I have implemented it using the default state
https://github.com/user-attachments/assets/18fdc878-278c-4f67-aa80-b18b661473a3
=> Corrected player detection on place block

pumpkin-nbt/src/serializer.rs, pumpkin-util/src/text/mod.rs, pumpkin-util/src/translation.rs, pumpkin/src/command/args/arg_textcomponent.rs, pumpkin/src/command/commands/cmd_deop.rs, pumpkin/src/command/commands/cmd_fill.rs, pumpkin/src/command/commands/cmd_gamemode.rs, pumpkin/src/command/commands/cmd_give.rs, pumpkin/src/command/commands/cmd_kick.rs, pumpkin/src/command/commands/cmd_kill.rs, pumpkin/src/command/commands/cmd_list.rs, pumpkin/src/command/commands/cmd_op.rs, pumpkin/src/command/commands/cmd_setblock.rs, pumpkin/src/command/commands/cmd_stop.rs, pumpkin/src/command/commands/cmd_teleport.rs, pumpkin/src/command/commands/cmd_time.rs, pumpkin/src/command/commands/cmd_worldborder.rs, pumpkin/src/entity/player.rs, pumpkin/src/net/mod.rs, pumpkin/src/net/packet/handshake.rs, pumpkin/src/net/packet/login.rs, pumpkin/src/net/packet/play.rs, pumpkin/src/world/mod.rs
Changed the whole TextComponent structure to allow nested translated texts and avoid recursion in serialization, but keeping the api unchanged. Also changed all the translate components to fit the new format, and added translation to gamemode command.
Truly happy of beign able to solve this issue, the TextComponent had two problems:
1. It had a loop in its serialization, being that TC::serialize called to_bytes_unnamed and this in turn called TC::serialize again.
2. As it has to be converted to bytes (or so I understand) when serializing, the children and translation arguments were converted twice, which generated problems when reading it in the client.
> After having achieved this achievement (considering that I have just
started programming in rust) I am extremely happy to go to sleep. …
=> Text component refactor

pumpkin/src/command/commands/cmd_seed.rs, pumpkin/src/command/commands/cmd_time.rs, pumpkin/src/command/commands/cmd_worldborder.rs, pumpkin/src/net/query.rs, pumpkin/src/server/mod.rs
This PR wraps the
```rs
worlds: vec![Arc::new(world)]
```
field in the `Server` struct in a `RwLock`, to allow mutable access to the worlds field (to enable actions like adding and removing worlds from the server)
=> Make worlds field mutable using RwLock

pumpkin-protocol/src/lib.rs, pumpkin-util/src/text/hover.rs, pumpkin-util/src/text/mod.rs, pumpkin/src/command/commands/cmd_plugin.rs, pumpkin/src/command/commands/cmd_plugins.rs, pumpkin/src/command/commands/cmd_pumpkin.rs, pumpkin/src/command/commands/cmd_seed.rs, pumpkin/src/net/packet/login.rs
On the HoverEvents changed the ShowText type to allow using TextComponent on it, made the same chage to the "name" attribute of ShowEntity. 
> [!CAUTION]
> This solution perhaps is not the most suitable, since it is more a workaround, I explain, since when passing a single TextComponentBase the game is not able to read it, we take advantage of the fact that we can pass an array of them so the error doesn't jump, but this forces us to use Vec instead of Box.
In the seed command, the hover message has been changed so it will be translated as its behavior in vanilla.
Also fixed the "get_text" function from TextComponent to make it possible to use translations on it.
**Translated hover text of seed command (In spanish (●'◡'●))**
**Showing that translations works on ShowEntity (Using the seed …
=> Changed hover types

pumpkin/src/entity/player.rs, pumpkin/src/net/packet/play.rs
Move gamemode-specific ability logic from Abilities struct directly into 
Player::set_gamemode for better control flow. This fixes a bug where 
players would lose creative flight ability after death/respawn.
- Remove Abilities::set_for_gamemode method
- Handle ability changes directly in Player::set_gamemode
- Ensure Creative mode properly enables flight abilities
- Maintain proper ability state through death/respawn cycles
The previous implementation could lose flight ability state during 
respawn because ability updates were handled indirectly. By moving
this logic into Player::set_gamemode, we ensure consistent ability
state when changing gamemodes or respawning.
=> Fix creative flight after death

pumpkin-data/build/entity_type.rs, pumpkin-util/src/text/hover.rs, pumpkin-world/src/item/item_registry.rs, pumpkin/src/command/commands/bossbar.rs, pumpkin/src/command/commands/clear.rs, pumpkin/src/command/commands/give.rs, pumpkin/src/command/commands/kill.rs, pumpkin/src/command/commands/mod.rs, pumpkin/src/command/commands/msg.rs, pumpkin/src/command/commands/pumpkin.rs, pumpkin/src/command/mod.rs, pumpkin/src/entity/player.rs, pumpkin/src/world/custom_bossbar.rs
Added parity with vanilla to texts from the following commands:
- Clear
- Kill
- Give
- Msg
The pumpkin command has also been formatted to make it more readable.
Other minors changes are:
1.  Updated show_entity from HoverEvents to make it easier to use.
2.  On EntityType added to_str and to_string which returns the identifier of the entity. (Resource location)
3.  On item added translated_name which returns the TextComponent::translate suitable for that item.
Note: Many of the changes requires [F3 + H] (Advanced Tooltips) to be shown.
Added msg command to match with the changes above, for its implementation the function send_message was added to Player.
**Pumpkin commands**
**Player selection and tell**
**Item show**
**Msg command**
Please follow our [Coding …
=> Command parity to vanilla

pumpkin/src/net/mod.rs, pumpkin/src/net/packet/config.rs, pumpkin/src/net/packet/login.rs
Moved `can_not_join` check from login state to end of configuration.
This fixes the "Missing GameProfile" issue, when using velocity, reported on discord.
Joining both on velocity and without a proxy, while being banned/not banned.
=> Velocity missing game profile

egg-pumpkin.json
=> Add egg-pumpkin.json

pumpkin/src/net/packet/play.rs
Some code was left out of an if statement causing unexpected behaviour, eg. if a plyer stood in the way of a block it would not place but still decrement the players items.
=> Fixed item decrementing while block fails to place due to player intersection

pumpkin/src/block/properties/cardinal.rs, pumpkin/src/block/properties/waterlog.rs, pumpkin/src/net/packet/play.rs
Added the ability to waterlog blocks when you place them on water, or when you use a bucket.
Also repaired the properties to fences/walls, which were broken due to a error on the rework properties transfer
=> Mini properties repair

pumpkin-data/build/entity_type.rs, pumpkin-util/src/text/hover.rs, pumpkin/src/command/commands/clear.rs, pumpkin/src/command/commands/give.rs, pumpkin/src/command/commands/kill.rs, pumpkin/src/command/commands/msg.rs
Give valid entity type to HoverEvent::show_entity calls.
Previously, executing a command such as /give, /msg, etc would cause the client to close connection because of an invalid entity type in HoverEvent within the chat message sent to the player.
Modified pumkin-data to expose the resource name of entities.
Also made the `kind` parameter not `Option`, because a value of `None` also causes the client to crash.
https://github.com/user-attachments/assets/4f514ad9-27da-478a-b311-881bd84936cb
https://github.com/user-attachments/assets/b0a64455-6c03-4f95-a984-976155aaed5c
=> Fix HoverEvent::show_entity calls

pumpkin/src/entity/player.rs, pumpkin/src/net/container.rs, pumpkin/src/net/query.rs, pumpkin/src/plugin/api/context.rs, pumpkin/src/server/mod.rs, pumpkin/src/world/mod.rs
This PR changes the `players` field in the `World` struct:
```rs
pub struct World {
/// A map of active players within the world, keyed by their unique UUID.
pub players: Arc<Mutex<HashMap<uuid::Uuid, Arc<Player>>>>,
}
```
from a `Mutex` to a `RwLock`.
This fixes a couple deadlocks which can cause the player to time out and be unable to join the server again. Specifically any function called from within the `player.tick()` method which also broadcasted packets to players on the server would cause a deadlock as the `world.broadcast_packet_all` method (and similar) require a lock to the `players` mutex, but this mutex is already locked by the `world.lock()` method which calls `player.tick()`.
This change also theoretically helps prevent other similar deadlocks, as the only cases where …
=> Make the players field in World use RwLock instead of Mutex

pumpkin/src/command/commands/help.rs
This PR modifies the help command to also filter commands based on if the command sender has permission to execute said command.
=> Only show commands that player can execute

pumpkin/src/entity/player.rs, pumpkin/src/net/packet/play.rs
Add support for `DropItem` and `DropItemStack`. (Also prevents item dupe glitch where it would always drop the stack but only subtract a single item)
=> Differentiate between single and stack drops

pumpkin/src/entity/living.rs
Scrolling quickly in the hotbar in the current version desyncs the client. By not sending equipment updates to the player it won't desync
=> Don't boradcast Equipment Change back to player

pumpkin-world/src/level.rs, pumpkin/src/lib.rs, pumpkin/src/net/mod.rs
When the send packet function is invoked on the client, the lock on the encrypter was unnecessarily held for the remainder of the function. When a notification was sent to the `server_packets_channel`, the encrypter lock was still held, preventing the serialized packet from being taken and blocking the next call to the send packet function
You can verify this worked by teleporting to the world border.
Before: Deadlock
Now: Normally chunk loading
=> Fix deadlock when "packet ready" buffer is full

pumpkin-world/Cargo.toml, pumpkin-world/benches/chunk_noise_populate.rs, pumpkin-world/src/level.rs, pumpkin-world/src/lib.rs
Benchmarks chunk IO based on the current `./config` settings. 
Removed spawning an async task for saving chunks because otherwise the benchmark would not be accurate
=> Chunk io benchmarking

pumpkin-protocol/src/client/play/spawn_entity.rs
Title, changes the Y and Z fields in the Vector3 constructor to use their respective velocity fields instead of the X velocity. Probably a tired copy & paste oversight, remember to take breaks and stay hydrated!
Cheers to the team! :)
Found whilst looking for issue with ThrownItemEntity's trajectory, said trajectory now seems to work as intended, haven't tested it with other mobs due to the lack of AI but shouldn't be an issue.
=> Fix entity velocity in Client Play Entity Spawn packet

pumpkin-api-macros/src/lib.rs
In rust edition 2024, the `#[no_mangle]` attribute was made unsafe. This PR wraps the `no_mangle` attribute used within the `pumpkin-api-macros` crate with `#[unsafe(no_mangle)]` to fix rust complaining about it being unsafe.
=> Add the unsafe attribute to no_mangle in plugin method generation

pumpkin-api-macros/src/lib.rs
I am sorry for missing this in #622 but there are two instances of `#[no_mangle]` being used in the api-macros crate, this pr fixes the other one as well
In rust edition 2024, the `#[no_mangle]` attribute was made unsafe. This PR wraps the `no_mangle` attribute used within the `pumpkin-api-macros` crate with `#[unsafe(no_mangle)]` to fix rust complaining about it being unsafe.
=> Fix other no_mangle

pumpkin-config/Cargo.toml, pumpkin-config/src/chunk.rs, pumpkin-config/src/lib.rs, pumpkin-world/Cargo.toml, pumpkin-world/benches/chunk_noise_populate.rs, pumpkin-world/src/chunk/format/anvil.rs, pumpkin-world/src/chunk/format/linear.rs, pumpkin-world/src/chunk/format/mod.rs, pumpkin-world/src/chunk/io/chunk_file_manager.rs, pumpkin-world/src/chunk/io/mod.rs, pumpkin-world/src/chunk/mod.rs, pumpkin-world/src/generation/generic_generator.rs, pumpkin-world/src/generation/implementation/test.rs, pumpkin-world/src/level.rs, pumpkin/src/entity/living.rs, pumpkin/src/entity/player.rs, pumpkin/src/lib.rs, pumpkin/src/net/authentication.rs, pumpkin/src/net/lan_broadcast.rs, pumpkin/src/net/packet/config.rs, pumpkin/src/net/packet/login.rs, pumpkin/src/net/packet/play.rs, pumpkin/src/net/query.rs, pumpkin/src/net/rcon/mod.rs, pumpkin/src/server/mod.rs, pumpkin/src/world/mod.rs
This PR does several things:
* Adds a `dirty` flag to chunk data such that ChunkIO can see if a chunk has been modified when determining whether or not to write it
* Adds a config option of `write_in_place` for chunks. If this is true (it defaults false), the Anvil chunk serializer will attempt to write chunks within the file instead of writing an entirely new file.
* Pros: a lot less file I/O and at lot faster
* Cons: **IF** the server shuts down uncleanly *while* a write is being done, the chunks being written *may* be corrupted rather than rolled back to the original save.
* Adds a method to ChunkSerializers to determine whether or not they should write to file when chunks are sent to them.
* Separates spawn chunks from watched chunks
* Add a type to the ChunkSerializer trait to denote …
=> ChunkIO api and world saving optimizations

pumpkin-util/src/math/position.rs, pumpkin/src/block/blocks/tnt.rs, pumpkin/src/world/explosion.rs
A lot of small mistakes were in the previous impl, fixed for performance and validity
- Used HashSet instead of Vector to reduce calculations when going through all blocks to destroy them
- Added @FlorianLang06 's yz-fix Where y and z were used wrong.
- Aligned code more to how Java does it
- Added 0.0625 to Y as java does it. (0.0625 * entity height)
- Added velocity, but this won't look right until velocity is implemented.
Only in-game testing
=> Rewrote TNT logic

pumpkin/src/command/commands/kill.rs, pumpkin/src/entity/player.rs
This PR fixes #541. After a player was killed the PLAY_PLAYER_COMBAT_KILL packet will be send to the player. This means the player sees the respawn screen even if he has the chat open or is in the menu. The sending of this packet was already implemented in the kill function of the player but this function was never used.
To achieve this I changed that in the kill command use the kill function of the player and after a damage of a player it will be check if the player is death and the packet will also be send.
The only way a player can still be killed without this packet is if the kill method of the living entity is directly called.
=> Show player respawn screen if the chat or menu is open

pumpkin-world/src/biome/multi_noise.rs, pumpkin-world/src/generation/aquifer_sampler.rs
Apperently it overrided the biome params for some reason
=> Fix bug in get_enclosing_parameters

pumpkin-world/src/generation/surface/terrain.rs
Fix terracotta bands missing in badlands generation
This was observed by comparing badlands structures on vanilla against pumpkin. Pumpkin band generation now matches vanilla.
**Before**
**After**
=> fix badlands band generation

pumpkin-world/src/chunk/mod.rs, pumpkin/src/world/mod.rs
Server previously would crash if any player was below y -64 (bedrock).
Fixes https://github.com/Pumpkin-MC/Pumpkin/issues/651
ChunkBlocks.get_block now returns the ID for AIR under y level -64
**Note:** This does not implement player damage under y -128. It simply fixes the BlockOutOfWorldBounds error. Player will fall forever in current state.
**EDIT:** The actual issue is the lowest level of bedrock (y=-64) tries to update neighbors on y=-65 which doesn't exist.
=> Fixes BlockOutOfWorldBounds server crash when bedrock gets updated

pumpkin/src/block/blocks/redstone/buttons.rs
Implemented the `use_with_item` function for buttons and return `BlockActionResult::Consume` in it to prevent placing of blocks if a player clicks on button with item in hand. This is the same logic as for a switch. 
=> Don't place block if button will be clicked with item in hand

pumpkin-config/src/lib.rs, pumpkin-nbt/src/tag.rs, pumpkin-protocol/src/client/play/commands.rs, pumpkin-world/src/cylindrical_chunk_iterator.rs, pumpkin/src/entity/player.rs, pumpkin/src/net/mod.rs, pumpkin/src/net/packet/config.rs, pumpkin/src/net/packet/play.rs, pumpkin/src/world/chunker.rs
Refactored a few simple and unnecessary uses of unsafe and added some explicit safety comments.
Should have zero impact on performance or behaviour, and reduces unsafe blocks from 19 -> 7.
5/7 of which being used for plugin libloading.
Changed nonzero integer literal `NonZero<u8>` initializations from `NonZeroU8::new_unchecked(1)` to `NonZeroU8::new(1).unwrap()` syntax, as compiler is able to [optimize](https://godbolt.org/z/MoMzTGsnd) to a no-op at `opt-level=1`
Similar to above but for after conditional statement checking nonzero-ness of number, as compiler can also [optimize](https://godbolt.org/z/v8j9Psozb) to a no-op at `opt-level=1`
Changed `NonZeroU8::new_unchecked(..)` use in unit tests to `NonZeroU8::new(..).unwrap()` syntax
Added explicit safety comments about unsafe pointer …
=> Refactor unnecessary unsafe code and add safety comments

pumpkin/src/net/packet/play.rs
During fluid flow testing, we discovered that the handling for creative breaking was not sending the updates. This would put the client in a state of assuming the block wasn't broken yet, so it would remain empty on the client side, even when told that it wasn't empty.
Manual
=> Fix creative block breaking bug

pumpkin/src/plugin/api/events/block/block_break.rs, pumpkin/src/world/mod.rs
This adds a new field block_position to the BlockBreakEvent, which would allow plugins listening to this event to see information on the location of the block.
=> Add block_position to BlockBreakEvent

pumpkin-data/build/item.rs
Parse minecraft:food - nutrition, saturation, and can_always_eat - from items.json and add it to ItemComponents
Passed cargo clippy --all-targets
Passed cargo test
=> Add food components to item

pumpkin/src/entity/player.rs, pumpkin/src/world/mod.rs
Use undefined previous gamemode on join to let the client decide which gamemode to switch to.
Fixes #718 
Could not reproduce the bug
=> Fix gamemode switcher

pumpkin/Cargo.toml
Fixes [ #594](https://github.com/Pumpkin-MC/Pumpkin/issues/594).
Fixed in [commit 6dda634](https://github.com/zyansheep/rustyline-async/commit/6dda63402becfcfa11968a3531e8a17aed3ec994) in [rustyline-async](https://github.com/zyansheep/rustyline-async).
Isn't pushed to [crates.io](https://crates.io/crates/rustyline-async) so I pinned [rustyline-async](https://github.com/zyansheep/rustyline-async) to commit [6dda634](https://github.com/zyansheep/rustyline-async/commit/6dda63402becfcfa11968a3531e8a17aed3ec994).
Passes docker build after regenerating lockfile
=> Fix rustyline-async division by zero panic

pumpkin/src/entity/living.rs
Make so the server doesn't send death packets every tick after a living entity is dead, even if the entity were to tick after it's supposed removal.
Fixes #728 
Slam myself into the ground in survival mode, could not replicate mentioned issue.
=> Fix rubberbanding after death

pumpkin/src/block/blocks/redstone/redstone_wire.rs, pumpkin/src/block/blocks/redstone/repeater.rs
(edited after I realized a part of what I was doing was probably out of the scope of this PR)
This pull request introduces the following change:
1. **Power Check for Repeater Placement**: Added code to check if a repeater should be powered on placement.
This fixes #762. For example if you try having a redstone torch and then place a repeater, it will be placed in a powered state.
I tested manually, not sure if I need to do more
=> Fixing repeater power on placement

pumpkin-world/src/entity/entity_data_flags.rs, pumpkin-world/src/entity/mod.rs, pumpkin-world/src/lib.rs, pumpkin/src/command/commands/pumpkin.rs, pumpkin/src/data/player_server_data.rs, pumpkin/src/entity/player.rs, pumpkin/src/lib.rs, pumpkin/src/net/mod.rs, pumpkin/src/net/packet/play.rs, pumpkin/src/plugin/api/context.rs, pumpkin/src/server/connection_cache.rs, pumpkin/src/server/mod.rs, pumpkin/src/world/chunker.rs, pumpkin/src/world/mod.rs
Fix `world.players` dead lock on stress test, by releasing read locks as early as possible.
Most players read locks has been replaced with `world.current_players()`, which returns a copy of current players in a `Vec`. I have not yet documented to warn developers do not use players directly in read only operations.
This PR also fixed a typo in `/pumpkin`
=> Fix dead lock

pumpkin/src/entity/mod.rs
When looking straight down, placing an observer is often not possible, so I tried to figure out why.
With the decompiled code I found the function `get_facing()` in Pumpkin seems to be based upon (`orderedByNearest`). I replaced the current one with the implementation almost exactly to vanilla without optimizing for now, with the exception that vanilla returns an array of nearest directions, which might be useful in the future, I don't know.
This fixes observer and piston placements.
I tested with python. I have the java function and my function. For each case, I generate random angles:
```python
pitch = random.uniform(-90, 90)
yaw = random.uniform(-180, 180)
```
I run `100000000` iterations (if you plan on running this, probably lower this).
I don't know if I should add it to the …
=> observer and piston placement fix (get_facing)

pumpkin/src/entity/living.rs
Fix the initial last_pos of a LivingEntity.
In LivingEntity::new(), set last_pos to entity.pos instead of 0,0,0.
This is important because otherwise, when first sending position of a new mob, assuming you use the difference _pos - last_pos_ to send position, the entity will appear to jump somewhere else.
Passed cargo check, cargo fmt --check, and cargo test.
=> Fix last_pos of new LivingEntity

pumpkin-protocol/src/server/play/player_position.rs, pumpkin-protocol/src/server/play/player_position_rotation.rs, pumpkin/src/net/packet/play.rs
Fix #781 
`is_infinite` does not check for NaN, so use `!is_finite` instead.
The original report is wrong: We have checked for NaN position before clamping, but there is still a NaN rotation.
Have not tested yet.
=> Fix NaN rotation in player move packets

pumpkin/src/block/blocks/chest.rs
Fixed an issue where chests connect when you shift click on another double chest (creating a triple chest).
Manual
=> Chest placement fix

pumpkin/src/command/args/bounded_num.rs, pumpkin/src/command/commands/effect.rs, pumpkin/src/command/commands/give.rs, pumpkin/src/command/commands/help.rs, pumpkin/src/command/commands/particle.rs, pumpkin/src/command/commands/transfer.rs
This commit fixes the server crash on invalid arguments for the effect command, hower it does not provide translation support for the error message and also doesn't change a lot of other things, the primary goal here is really just to fix this one crash.
Previously you could just crash the Pumpkin server by providing an invalid value for a bounded argument when using the `effect` command. Error handling for `give`, and `particle` was also inconsistent.
In the handler for `particle` the server just ignored the invalid argument and used defaults instead which is not the same behaviour that the java server exhibits.
Give just didn't provide the proper error message, also note that the current upper bound for the command is `i32::MAX` which is not the same as in the java server, this PR …
=> Fix effect command crashing the server because of invalid bounds

pumpkin-config/src/commands.rs, pumpkin/src/lib.rs
This PR allows reading commands from stdin. Stdin is very important since many server hosting softwares redirect stdin and executing console commands that way.
Without this PR, any commands in non-tty mode will be simply ignored.
When the user press Ctrl+C, the signal is correctly captured, and the server saves and stops. However, since `stdin().read_line` is blocking, it waits for a newline if there is not a newline. Users may have to press an extra enter to fully close the server. Server hosting softs that send a `stop` command via stdin will not be effected.
=> Read commands from stdin

pumpkin/src/entity/mod.rs
Fixes the `called 'Result::unwrap()' on an 'Err' value: BlockOutOfWorldBounds` error by replacing the `.unwrap()` call with a if statement:
```rs
if let Ok((block, state)) = world.get_block_and_block_state(&pos).await {
world
.block_registry
.on_entity_collision(block, &world, entity, pos, state)
.await;
}
```
=> Fix called `Result::unwrap()` on an `Err` value: BlockOutOfWorldBounds

pumpkin-util/src/math/mod.rs
There was an usize overflow error in compile time, due it is 32 bits for 32 bit arch, so I made it 64 bits, then casted to usize
I tested nothing
=> Fixed overflow for 32 bits

pumpkin/src/world/mod.rs
Server crashes in case of blocks being placed in various ways outside acceptable y bounds.
So I removed scary .unwrap()
=> removed scary unwrap

pumpkin/src/world/mod.rs
This PR was made to resolve [this issue](https://github.com/Pumpkin-MC/Pumpkin/issues/801).
When a player first spawns in a world, their y coordinate is set to 200, which typically results in their death on the first spawn. To address this issue, I modified the player’s spawning mechanism to ensure they spawn on the top block of the x and z coordinates. However, this modification, coupled with the current codebase, caused the player to spawn on the top block, but since the chunk generation occurred after the player spawned, the player would glitch out of the map. Consequently, I implemented a change to generate the chunk and send it to the client before the player spawns. 
Please follow our [Coding Guidelines](https://github.com/Pumpkin-MC/Pumpkin/blob/master/CONTRIBUTING.md#coding-guideli …
=> fix: spawn player on top block instead of 200 y (#801)

Cargo.lock, pumpkin-util/Cargo.toml, pumpkin-util/src/permission.rs, pumpkin/src/command/client_suggestions.rs, pumpkin/src/command/commands/help.rs, pumpkin/src/command/commands/mod.rs, pumpkin/src/command/dispatcher.rs, pumpkin/src/command/mod.rs, pumpkin/src/entity/player.rs, pumpkin/src/lib.rs, pumpkin/src/main.rs, pumpkin/src/plugin/api/context.rs, pumpkin/src/server/mod.rs
This PR implements a string-based, namespaced permission system (not only) for commands.
Permissions are prefixed with a namespace, that can either be:
- `minecraft:` for vanilla builtin commands
- `pumpkin:` for builtin commands that have been added on top of vanilla
- or when used with plugins, the plugin identifier is used (plugins may only register permissions within their namespace, there is a workaround, but it is only intended for advanced use cases)
The value of each permission is a list of identifiers separated by the `.` character. There can be as many identifiers as necessary.
When registering a permission, the default value must be provided. This can be one of:
- `PermissionDefault::Allow` - which will allow the permission by default
- `PermissionDefault::Deny` - which will …
=> Implement string-based permission system

pumpkin/src/entity/living.rs
When testing i found a bug where you take fall damage when landing on powdered snow, which shouldn't happen.
Added quick check to remove fall damage when landing on the block.
Tested it in game, also tested how fall damage works after landing on the block in the air. Everything is good except the view is reacting like the powdered snow wasnt there, but you take the correct fall damage.
=> Removed fall damage when landing on powdered snow

pumpkin-world/src/chunk/mod.rs, pumpkin-world/src/level.rs, pumpkin/src/world/mod.rs
Level::is_block_tick_scheduled did not detect block-ticks that will be executed later in the current tick,
leading to incorrect behavior of redstone torches and repeaters, like redstone torches
reacting to 2 gametick pulses, and repeaters in some cases flashing when being turned off. 
is_block_tick_scheduled should detect block-ticks that will be executed later in the current tick,
but not detect block-ticks that were already processed.
To implement this, is_block_tick_scheduled needs to know which block-ticks were already executed
by the World::tick_scheduled_block_ticks function in the current tick, therefore we store the block-ticks,
that still need to be processed in a field in the Level called "remaining_block_ticks_this_tick", where both
methods can access it.
This is to kind of …
=> Fix issue with Level::is_block_tick_scheduled, related to problems with redstone.

.github/workflows/docker.yml, pumpkin-data/build/build.rs
This should fix the problem that the pumpkin-data build script can sometimes produce empty files.
added a hard error if writing to a file returns an error other than interrupted.
=> hopefully fix for miss generating files

pumpkin/src/net/packet/play.rs
Call use_with_item before use_on_block like vanilla.
Fixed #875.
All existing test passed.
Test manually about #875.
=> fix: Call use_with_item before use_on_block like vanilla

pumpkin-inventory/src/screen_handler.rs, pumpkin/src/entity/player.rs, pumpkin/src/net/packet/play.rs
Fix deadlock when throwing items #865
`self.current_screen_handler.lock().await;` should do first otherwise cause deadlock in tick() (this thread lock stack and wait screen_handler. that thread lock screen_handler and wait stack)
In addition, i notice `screen_handler.get_slot_index` and `screen_handler.set_received_stack` don't use any async fn in them but are marked as async. Should i remove async mark of the two fn?
=> Fix deadlock when throwing items (#865)

pumpkin/src/net/packet/play.rs
After the player respawns, items that were originally in the backpack are not visible in the client's hotbar. However, they can still be placed by right-clicking.
This bug is mentioned in the issue: https://github.com/Pumpkin-MC/Pumpkin/issues/876
=> fix: Server and client inventories out of sync after respawn_player

pumpkin/src/item/items/axe.rs
The function to get the stripped version of a log/wood was not complete.
Should have been done when this was originally written but it works now.
=> Fix Stripping Logs

pumpkin/src/plugin/api/context.rs
Improves `get_data_folder` method by returning the Path and using `join` to get the plugin's specific path instead of format 
No failures
=> Improve data folder method

pumpkin/src/item/items/ignite/ignition.rs
For some reason we were discarding the rest of the block state values when getting the new block state... which meant that for example the campfire rotation is reset.
Ingame
=> Fix Resetting of Block States

flake.lock, flake.nix
When using NixOS and VS Code with the `flake.nix` file, the Rust Analyzer extension cannot locate the Rust standard library. This pull request updates `flake.nix` so that it always installs the standard library, which resolves the issue. In addition, I have updated the Nix flake to the latest version.
Before this change, I encountered the error:
`ERROR: can't load standard library; try installing rust-src sysroot_path=/nix/store/f293vck2j3zf8rb8phc5zb08lsvihsff-rust-default-1.87.0`
After applying the change, the error no longer appears.
=> fix: Can't load standard library when using VSCode on NixOS

pumpkin/src/plugin/mod.rs
- When loading all Plugins make it so that when try_load_plugin fails that other plugins will still be loaded.
- Log loaded plugins
=> Skip unloadable plugins and log loaded plugins

pumpkin/src/entity/living.rs
The fall distance was not reset when the player fell into water or powder snow, causing the player to take damage when returning to the ground. 
The bug wasn't really in #507 but is similar.
In-Game testing
=> Fixed weird behavior of fall damage when player is in water #507

pumpkin-world/Cargo.toml, pumpkin-world/benches/noise_router.rs, pumpkin-world/src/generation/noise_router/chunk_density_function.rs
This PR significantly optimizes the performance of world generation by introducing a buffer pooling strategy for noise cache structures.
It addresses a bottleneck caused by frequent memory allocations during the creation of `ChunkNoiseRouter`.
During world generation, `ChunkNoiseFunctionComponent` are created for every chunk. These components allocated `f64` arrays on the heap for caching, leading to overhead from repeated allocation and deallocation cycles.
A new benchmark was added to measure the performance of `ChunkNoiseRouter::generate`. The results demonstrate a substantial improvement:
| Benchmark                                 | Before Optimization (µs) | After Optimization (µs) | Change      |
| ----------------------------------------- | ------------------------ | …
=> Optimization `ChunkNoiseFunctionComponent`

pumpkin-util/src/translation.rs
https://github.com/Pumpkin-MC/Pumpkin/issues/1077
When I placed the assets/en_us.json file from the source code into the assets directory relative to the pumpkin binary, it worked correctly.
So I used include_str!() to handle it.
=> fix: could not find en_us.json

pumpkin-data/Clippy.toml, pumpkin-data/build/attributes.rs, pumpkin-data/build/biome.rs, pumpkin-data/build/block.rs, pumpkin-data/build/build.rs, pumpkin-data/build/composter_increase_chance.rs, pumpkin-data/build/damage_type.rs, pumpkin-data/build/data_component.rs, pumpkin-data/build/effect.rs, pumpkin-data/build/enchantments.rs, pumpkin-data/build/entity_status.rs, pumpkin-data/build/entity_type.rs, pumpkin-data/build/flower_pot_transformations.rs, pumpkin-data/build/fluid.rs, pumpkin-data/build/fuels.rs, pumpkin-data/build/game_rules.rs, pumpkin-data/build/item.rs, pumpkin-data/build/loot.rs, pumpkin-data/build/message_type.rs, pumpkin-data/build/noise_parameter.rs, pumpkin-data/build/noise_router.rs, pumpkin-data/build/packet.rs, pumpkin-data/build/potion.rs, pumpkin-data/build/recipe_remainder.rs, pumpkin-data/build/recipes.rs, pumpkin-data/build/spawn_egg.rs, pumpkin-data/build/tag.rs, pumpkin-data/build/world_event.rs
I noticed that running `cargo check`, `cargo build`, and `cargo clippy` back-to-back would always rewrite the generated files. This slowed down incremental builds because crates that depended on those files had to be recompiled every time.
This was happening for three main reasons:
- Changing tools doesn't honor `cargo:rerun-if-changed`
-  We used HashMaps, which don't guarantee a consistent order.
-  We always rewrote the output file, even if the content was identical.
This PR fixes this by switching all the HashMaps in the build functions to BTreeMaps to ensure the output is always in the same order. I also added a lint to prevent anyone from accidentally using a HashMap here again.
Additionally, the script now checks if the file content has actually changed before writing. If it's the …
=> build: Make file generation deterministic & skip unchanged files

flake.lock, flake.nix
Like the title says, this fixes the flake that previously didn't break, adds rust-analyzer to the nix devshell and moves to fenix (a rust toolchain provider) from rust-overlay.
This doesn't affect any of the code and I have successfully built the nix package which should be reproducible.
=> Fix broken nix flake, add rust-analyzer to devshell and move to fenix from rust-overlay

pumpkin-protocol/src/java/client/login/login_disconnect.rs, pumpkin-protocol/src/java/client/play/player_position.rs, pumpkin-protocol/src/java/client/status/status_response.rs, pumpkin-protocol/src/java/packet_encoder.rs, pumpkin/src/entity/player.rs, pumpkin/src/net/java/mod.rs, pumpkin/src/net/java/play.rs, pumpkin/src/server/connection_cache.rs
I have removed lifetimes from CPlayerPosition and CStatusResponse. Input on what should happen to the other client packets with lifetimes is needed.
=> fix: Remove liftimes from CStatusResponse and CPlayerPosition
