Pumpkin-MC/Pumpkin

- .devcontainer/devcontainer.json
- .github/dependabot.yml
- .vscode/settings.json
This pull request enhances the development experience by combining essential development tools into a containerised environment. The goal is to ensure consistency and reproducibility of the development environment across different machines.
The only requirement is to have Docker installed on the host.
> Added Development Tools

- pumpkin-protocol/src/bytebuf/deserializer.rs
- pumpkin-protocol/src/bytebuf/mod.rs
- pumpkin-protocol/src/bytebuf/packet_id.rs
- pumpkin-protocol/src/lib.rs
- pumpkin-protocol/src/server/config/mod.rs
- pumpkin-protocol/src/server/config/s_acknowledge_finish_config.rs
- pumpkin-protocol/src/server/config/s_client_information.rs
- pumpkin-protocol/src/server/config/s_known_packs.rs
- pumpkin-protocol/src/server/config/s_plugin_message.rs
- pumpkin-protocol/src/server/handshake/mod.rs
- pumpkin-protocol/src/server/login/mod.rs
- pumpkin-protocol/src/server/login/s_encryption_response.rs
- pumpkin-protocol/src/server/login/s_login_response.rs
- pumpkin-protocol/src/server/login/s_login_start.rs
- pumpkin-protocol/src/server/login/s_plugin_response.rs
- pumpkin-protocol/src/server/play/mod.rs
- pumpkin-protocol/src/server/play/s_chat_command.rs
- pumpkin-protocol/src/server/play/s_confirm_teleport.rs
- pumpkin-protocol/src/server/play/s_player_command.rs
- pumpkin-protocol/src/server/play/s_player_position.rs
- pumpkin-protocol/src/server/play/s_player_position_rotation.rs
- pumpkin-protocol/src/server/play/s_player_rotation.rs
- pumpkin-protocol/src/server/play/s_swing_arm.rs
- pumpkin-protocol/src/server/status/mod.rs
- pumpkin-protocol/src/server/status/s_ping_request.rs
- pumpkin-protocol/src/server/status/s_status_request.rs
- pumpkin/src/client/mod.rs
- pumpkin/src/main.rs
Identical implementation as #17 but for deserializing server bound packets, for details look there.
> Add Deserializer for server bound packets

- pumpkin/src/server.rs
Vanilla's fly speed is 0.1 however here it is set to 0.2.
> Change fly speed to vanilla speed

- CONTRIBUTING.md
- README.md
* Change header levels
* If the old ones were intentional please do nit
* Add spaces between newlines
* Add language to code blocks
> docs: format markdown

- pumpkin-core/src/random/legacy_rand.rs
- pumpkin-core/src/random/mod.rs
- pumpkin-core/src/random/xoroshiro128.rs
Adds the legacy minecraft RNG and the java string hash
> implement legacy_random and java string hash

- pumpkin-inventory/src/player.rs
- pumpkin-protocol/src/lib.rs
- pumpkin-protocol/src/packet_encoder.rs
- pumpkin/src/client/client_packet.rs
- pumpkin/src/client/container.rs
- pumpkin/src/client/mod.rs
- pumpkin/src/client/player_packet.rs
- pumpkin/src/commands/arg_player.rs
- pumpkin/src/commands/cmd_echest.rs
- pumpkin/src/commands/cmd_gamemode.rs
- pumpkin/src/commands/mod.rs
- pumpkin/src/entity/mod.rs
- pumpkin/src/entity/player.rs
- pumpkin/src/main.rs
- pumpkin/src/proxy/velocity.rs
- pumpkin/src/server/mod.rs
- pumpkin/src/world/mod.rs
- pumpkin/src/world/player_chunker.rs
Finally. A Pumpkin without locks Problems.
This also allows the Tokio port to work.
> Solve Pumpkin's locking problem

- Cargo.toml
- pumpkin-config/Cargo.toml
- pumpkin-inventory/Cargo.toml
- pumpkin-protocol/Cargo.toml
- pumpkin-protocol/src/lib.rs
- pumpkin-registry/Cargo.toml
- pumpkin-world/Cargo.toml
- pumpkin/Cargo.toml
- pumpkin/src/client/mod.rs
- pumpkin/src/entity/mod.rs
- pumpkin/src/entity/player.rs
- pumpkin/src/server/connection_cache.rs
- pumpkin/src/world/mod.rs
Some typo fixes I've accumulated while working on my refactors. I'm being very lazy, and all the changes are in one bulk commit.
> misc spelling fixes in comments and variables

- .dockerignore
Fix failing build due to assets not found
> allow assets for docker build

- docs/config/basic.md
- pumpkin-config/src/lib.rs
- pumpkin/src/main.rs
adds an option to scrub IPs from logs
> Add config option to scrub ips from logs

- pumpkin-core/src/math/mod.rs
- pumpkin-core/src/random/gaussian.rs
- pumpkin-core/src/random/mod.rs
- pumpkin-world/src/world_gen/generic_generator.rs
- pumpkin-world/src/world_gen/noise/density/end.rs
- pumpkin-world/src/world_gen/noise/density/noise.rs
- pumpkin-world/src/world_gen/noise/density/spline.rs
- pumpkin-world/src/world_gen/noise/density/terrain_helpers.rs
- pumpkin-world/src/world_gen/noise/mod.rs
- pumpkin-world/src/world_gen/noise/perlin.rs
- pumpkin-world/src/world_gen/noise/simplex.rs
> Revert "Optimize floating point operations"

- pumpkin-protocol/src/bytebuf/mod.rs
- pumpkin/src/client/client_packet.rs
- pumpkin/src/client/mod.rs
- pumpkin/src/entity/player.rs
- pumpkin/src/main.rs
- pumpkin/src/proxy/velocity.rs
Fixed the support for velocity proxies
> Fixed velocity support

- pumpkin-world/src/cylindrical_chunk_iterator.rs
- pumpkin/src/entity/mod.rs
- pumpkin/src/world/player_chunker.rs
Fixed cylindrical so new chunks generate when you move around
> Fixed cylindrical

- pumpkin-world/src/chunk/anvil.rs
- pumpkin-world/src/chunk/mod.rs
- pumpkin-world/src/cylindrical_chunk_iterator.rs
- pumpkin-world/src/level.rs
- pumpkin/src/entity/player.rs
- pumpkin/src/main.rs
- pumpkin/src/world/mod.rs
- pumpkin/src/world/player_chunker.rs
This PR adds a counter to how many players are loading a chunks, unloading the chunk if no players are using them
> unload chunks when no players are using them

- pumpkin-core/src/math/position.rs
- pumpkin-inventory/Cargo.toml
- pumpkin-inventory/src/open_container.rs
- pumpkin/src/client/client_packet.rs
- pumpkin/src/client/container.rs
- pumpkin/src/client/mod.rs
- pumpkin/src/client/player_packet.rs
- pumpkin/src/proxy/velocity.rs
- pumpkin/src/rcon/mod.rs
- pumpkin/src/world/mod.rs
- pumpkin/src/world/player_chunker.rs
- turned dbg!("todo") into todo!()
- turned dbg! statements into log::debug! statements
- added logging to pumpkin-inventory
- added logging when a client tries to interact with a block out of reach
> Added better and more descriptive logging

- pumpkin-world/src/level.rs
- pumpkin/src/client/client_packet.rs
- pumpkin/src/client/mod.rs
- pumpkin/src/entity/player.rs
- pumpkin/src/main.rs
- pumpkin/src/world/mod.rs
- pumpkin/src/world/player_chunker.rs
This PR just adds more debug messages to packets.
Main use right now will be debugging my server, but can be helpful in the future
> More debug messages for packets

- pumpkin-core/src/math/position.rs
- pumpkin-protocol/src/client/play/c_chunk_data.rs
- pumpkin-world/src/chunk/anvil.rs
- pumpkin-world/src/chunk/mod.rs
- pumpkin-world/src/coordinates.rs
- pumpkin-world/src/level.rs
- pumpkin/src/client/player_packet.rs
- pumpkin/src/world/mod.rs
- pumpkin/src/world/player_chunker.rs
In this PR, I aim to add support for fast asynchronous placing & breaking of blocks.
> Block breaking and placing

- Cargo.toml
- pumpkin/src/main.rs
- pumpkin/src/server/ticker.rs
Currently, the ticking system blocks the whole thread.... this fixes that
> fix tick system

- pumpkin/Cargo.toml
- pumpkin/src/commands/cmd_echest.rs
- pumpkin/src/commands/cmd_gamemode.rs
- pumpkin/src/commands/cmd_help.rs
- pumpkin/src/commands/cmd_kick.rs
- pumpkin/src/commands/cmd_kill.rs
- pumpkin/src/commands/cmd_pumpkin.rs
- pumpkin/src/commands/cmd_stop.rs
- pumpkin/src/commands/dispatcher.rs
- pumpkin/src/commands/mod.rs
- pumpkin/src/commands/tree.rs
- pumpkin/src/commands/tree_builder.rs
- pumpkin/src/server/mod.rs
This PR fixes and makes commands async
> make commands async

- pumpkin/src/server/connection_cache.rs
> connection_cache: alter favicon logging

- pumpkin/src/client/player_packet.rs
- pumpkin/src/commands/arg_player.rs
- pumpkin/src/commands/cmd_echest.rs
- pumpkin/src/commands/cmd_gamemode.rs
- pumpkin/src/commands/cmd_help.rs
- pumpkin/src/commands/cmd_kick.rs
- pumpkin/src/commands/cmd_kill.rs
- pumpkin/src/commands/cmd_pumpkin.rs
- pumpkin/src/commands/cmd_stop.rs
- pumpkin/src/commands/dispatcher.rs
- pumpkin/src/commands/mod.rs
- pumpkin/src/commands/tree.rs
- pumpkin/src/commands/tree_builder.rs
- pumpkin/src/world/mod.rs
This makes command argument consumers async
> make command arg consumers async

- docs/.vitepress/config.mts
- docs/developer/world.md
- package-lock.json
I wrote a little documentation on what different world formats are and linked articles that could be used to read more.
I can make any change that is needed. No code was added, only documentation
> Added World Documentation

- Cargo.toml
- pumpkin-protocol/Cargo.toml
- pumpkin-protocol/src/client/play/c_chunk_data.rs
- pumpkin-world/src/chunk/mod.rs
- pumpkin/src/main.rs
Optimized CChunkData::write
Now creating rayon threads before the tokio runtime
Added profiling profile
> CChunkData optimizations

- docs/developer/world.md
Fixed a spelling error in docs
Docs needs no testing (I think)
> Fix spelling error

- docs/.vitepress/config.mts
- docs/config/advanced.md
Updated the docs to include the new config options for query protocol (#218) 
Added a navigation bar to the top of the page so that people can find the docs easier
A description of the tests performed to verify the changes:
Built the docs and checked what it would look like
> Update docs for new config options from implementing query protocol, added navigation bar

- pumpkin-core/src/text/mod.rs
- pumpkin-world/src/chunk/mod.rs
The Minecraft Fandom Wiki is deprecated. The new Minecraft Wiki has moved to https://minecraft.wiki/
Manually checked every link and content to match the old Fandom Wiki.
> Updated source code comments to use the new Minecraft Wiki

- pumpkin-core/src/text/mod.rs
Add hyperlinks to the terminal
> Term hyperlinks

- Dockerfile
- pumpkin/Cargo.toml
- pumpkin/build.rs
- pumpkin/src/command/commands/cmd_pumpkin.rs
- pumpkin/src/main.rs
Add current git commit hash to version info and print system info at startup for better bug traceability.
Removed ms in log timestamp, because it is unnecessary.
Ran inside docker and on windows11
> Logging system info

- Cargo.toml
> Upgrade thiserror

- docs/about/quick-start.md
As discussed on discord I've adapted the documentation to use the `docker compose` deployment method.
This deployment method has been verified on both Windows and Linux.
> docs: Update docker quick start steps

- pumpkin-core/src/math/position.rs
- pumpkin/src/command/commands/cmd_fill.rs
- pumpkin/src/command/commands/mod.rs
- pumpkin/src/command/mod.rs
Added the Fill command
Tested in-game and compared against vanilla java
> Add basic fill command

- .github/workflows/docker.yml
Started work on `docker.yml` for automatic docker image deployment on pushes to to branches (notably, excluding people's PRs). Aims to resolve #125.
Somewhat in the brainstorming and testing stages at the moment, lots of things here aren't final, e.g., what container registry is being selected.
A description of the tests performed to verify the changes:
- <https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages>
- <https://dev.to/fabiancdng/automatic-deployment-using-docker-and-github-actions-16fb>
- <https://docs.docker.com/build/ci/github-actions/manage-tags-labels/>
> workflows: begin work on docker image deployment

- .github/PULL_REQUEST_TEMPLATE.md
add checkboxes to pr template that remind authors of running + adding unit tests
see below
> Remind PR authors to add units tests

- docs/.vitepress/theme/style.css
- docs/index.md
Update Homepage and make everything orange
> Update Homepage and make everything orange

- pumpkin/src/command/commands/cmd_seed.rs
Use extra field in seed command for correct coloring.
> Use extra field in seed command

- pumpkin-core/src/text/mod.rs
Handle extra field in TextComponent to_pretty_console 
> Console text extra field

- pumpkin-core/src/text/mod.rs
- pumpkin/src/command/commands/cmd_help.rs
- pumpkin/src/command/tree_format.rs
A much nicer and more practical help command. 
Also adds pagination to help manage large numbers of commands.
Tested on local copy of server (arch linux)
> Better help command

- pumpkin/src/command/commands/cmd_pumpkin.rs
make it so you can coppy the server version on /version command
also changed the colors a bit
> make it so you can coppy the server version

- pumpkin-core/src/text/README.md
- pumpkin-core/src/text/color.rs
- pumpkin-core/src/text/mod.rs
- pumpkin-core/src/text/style.rs
Add shadow_color, new in 1.21.4
> Add shadow_color

- pumpkin/src/client/mod.rs
This PR makes it so the server does not attempt to encrypt and send a packet if the connection is closed
N/A
> check closed status before encrypting and sending assets

- pumpkin-inventory/Cargo.toml
- pumpkin-inventory/src/open_container.rs
- pumpkin/src/block/block_manager.rs
- pumpkin/src/block/blocks/chest.rs
- pumpkin/src/block/blocks/furnace.rs
- pumpkin/src/block/blocks/mod.rs
- pumpkin/src/block/mod.rs
- pumpkin/src/block/pumpkin_block.rs
- pumpkin/src/client/player_packet.rs
- pumpkin/src/entity/player.rs
- pumpkin/src/world/mod.rs
Added chest and furnace as interactive blocks (furnace does not produce any items)
Also added on_close function for interactive blocks for when client closes a container
Place chest, crafting table, and furnace
Place items in interactive blocks
Close interactive blocks and no client errors
> Added Chest and Furnace as Interactive Blocks

- Cargo.toml
- pumpkin-world/src/level.rs
Adding optimizations greatly increases build times for minimal benefit. This reverts that change.
N/A
> Remove optimizations for dev builds

- Dockerfile
Upgrade Alpine in Dockerfile to 3.21.
Fixes [CVE-2024-9143⁠](https://scout.docker.com/vulnerabilities/id/CVE-2024-9143?s=alpine&n=openssl&ns=alpine&t=apk&osn=alpine&osv=3.20&vr=%3C3.3.2-r1&utm_source=desktop&utm_medium=ExternalLink)
Docker build and run
> Upgrade Alpine to 3.21 (see CVE-2024-9143)

- pumpkin-data/build/biome.rs
- pumpkin-data/build/chunk_status.rs
- pumpkin-data/build/entity_pose.rs
- pumpkin-data/build/entity_type.rs
- pumpkin-data/build/game_event.rs
- pumpkin-data/build/noise_parmeter.rs
- pumpkin-data/build/packet.rs
- pumpkin-data/build/particle.rs
- pumpkin-data/build/scoreboard_slot.rs
- pumpkin-data/build/screen.rs
- pumpkin-data/build/sound.rs
- pumpkin-data/build/sound_category.rs
- pumpkin-data/build/world_event.rs
Fixes incremental builds for the generated `pumpkin-data` crate by pointing to the correct file paths
> Fix incremental build for `pumpkin-data` assets

- pumpkin/src/command/commands/cmd_time.rs
Implement Vanilla like literals for `/time set`.
Tested :)
> Implement /time set (day|noon|night|midnight)

- pumpkin/src/net/packet/play.rs
Trying to open the crafting table/furnace/etc before with an empty hand was not possible.
Slightly change the logic in `handle_use_item_on` (which probably should be renamed since the packet is sent on empty hands as well), so that it calls `PumpkinBlock::on_use` (previously never called).
Introduce a new `BlockPlacingError`: `NoBaseBlock`, since the use_item_on packet should (usually) have a base block.
Not sure how I can do that tbh, but existing tests still run.
> Open block GUI on empty hand interaction

- pumpkin-data/build/sound.rs
- pumpkin/src/command/args/bounded_num.rs
- pumpkin/src/command/args/mod.rs
- pumpkin/src/command/args/sound_category.rs
- pumpkin/src/command/commands/playsound.rs
This fully implements playsound to the best of pumpkins abilities from vanilla. I mostly looked at how other commands worked and modified it for playsound.
cargo test passes and I tested the command in game and it worked fine
> Finalize playsound command implementation

- pumpkin-data/build/sound.rs
Small change but should make it a bit faster
Ran cargo fmt & cargo clippy. Also tested in game and works as expected.
> Make sound "to_name" a constant function

- pumpkin-util/src/math/boundingbox.rs
- pumpkin-util/src/math/vector3.rs
- pumpkin-world/src/block/block_registry.rs
- pumpkin-world/src/block/mod.rs
- pumpkin/src/block/properties.rs
- pumpkin/src/net/packet/play.rs
Changed a little bit the properties system to make the slabs work properly and the collision calculation when placing them.
Now depends on the state calculations if the block is updatable or not, also now the calculus knows if the target block was clicked or was other. Also when the block is placed/updated from another block will have inverted the blockface to match the expected face of the block.
Alex: Also added "Layers" Property used for Stacking Snow (Bit buggy tho)
**Strange slabs pillars i made testing**
> Fixed slabs properties

- pumpkin/src/lib.rs
Log level now changes based on environment variables.
> Fix logging level

- pumpkin/src/lib.rs
simplify console logger initialization and add graceful fallback for Docker environments where terminal device or address is not available. 
previously identified an error while trying to spawn pumpkin in a docker container, the bug was introduced recently
```
thread 'main' panicked at pumpkin/src/lib.rs:84:63:
called `Result::unwrap()` on an `Err` value: IO(Os { code: 6, kind: Uncategorized, message: "No such device or address" })
stack backtrace:
```
> fix docker logger

- pumpkin-config/src/resource_pack.rs
- pumpkin/src/net/packet/config.rs
- pumpkin/src/net/packet/login.rs
Reverts resource pack field names
> revert resource pack names

- pumpkin/src/lib.rs
Fixes https://github.com/Pumpkin-MC/Pumpkin/issues/592
> Fix resource leak

- README.md
This pull-request changes the Readme To-Do to have some guideline on whether the feature is finished, in progress or not implemented.
No checkmark: Feature is not implemented and will not work yet
(W.I.P): The feature is there but is not behaving as intended.
Checkmark: The feature is working as intended, it could be improved, but the vanilla behavior is respected
I don't know if i've done some wrong WIP's or if one of the features listed as completed is not completed. Reviews would be appreciated
> Specify features state

- Dockerfile
- pumpkin-nbt/src/compound.rs
> Fix CI after rustup 1.28

- pumpkin-world/src/generation/noise_router/chunk_noise_router.rs
- pumpkin-world/src/generation/noise_router/multi_noise_sampler.rs
> Panic on invokation not creation of density function component for multinoise sampler

- pumpkin/src/block/blocks/jukebox.rs
This (small) PR just adds the logic for jukebox block properties (which are directly observable in some resource packs).
The jukebox still doesnt actually store the disc in NBT data (or pop out the disc once its removed), since block NBT isn't implemented yet
> Add Block Properties for Jukeboxes

- Cargo.toml
> Update to Tokio 1.44

- pumpkin/src/lib.rs
> fix players not being removed

- pumpkin-world/src/generation/proto_chunk.rs
> Surface generation fixes

- .dockerignore
- Dockerfile
Install git and add .git folder so git-version can determent the git commit we are on.
https://github.com/Pumpkin-MC/Pumpkin/blob/474eda33edcbb33306ac65746f38e1c1e491ce20/pumpkin/build.rs#L13-L18
> Use Git inside Docker build

- pumpkin-world/Cargo.toml
- pumpkin-world/src/generation/surface/mod.rs
> make vertical gradient condition thread local

- pumpkin/src/item/items/hoe.rs
Rewrite how the hoe work.
What are the changes:
- Dirt, grass and dirt path --> farmland
- Coarsed dirt --> dirt
- Rooted dirt --> dirt and drop hanging root (and depend on what is the clicked face). Also only the rooted dirt can be clicked from under the block
Place dirt, grass, dirt path, coarsed dirt and rooted dirt and use any type of hoe on it
> Make coarse and rooted dirt work as intended with the hoe

- .github/workflows/docker.yml
- Dockerfile
See https://docs.docker.com/build/ci/github-actions/annotations/
> Move Docker annotations to CI

- pumpkin/src/block/blocks/fluids/flowing_fluid.rs
Fixed two issues with water:
- 1-level water not disappearing
- weird spreading behaviour
manual
> Fix fluid weirdness

- pumpkin-world/src/chunk/format/anvil.rs
- pumpkin-world/src/chunk/format/linear.rs
- pumpkin-world/src/chunk/io/chunk_file_manager.rs
Adds better error handling to chunk (de)serialization and fixes file locks being removed early from the file manager
> Fix File IO Lock Manager

- .github/dependabot.yml
> Add docker to dependabot

- pumpkin-config/src/lib.rs
- pumpkin-config/src/networking/auth.rs
- pumpkin-protocol/Cargo.toml
- pumpkin-protocol/src/client/play/player_chat_message.rs
- pumpkin-protocol/src/client/play/player_info_update.rs
- pumpkin-util/src/math/mod.rs
- pumpkin-util/src/random/legacy_rand.rs
- pumpkin-util/src/random/mod.rs
- pumpkin-world/src/generation/seed.rs
- pumpkin/Cargo.toml
- pumpkin/src/entity/player.rs
- pumpkin/src/lib.rs
- pumpkin/src/net/authentication.rs
- pumpkin/src/net/mod.rs
- pumpkin/src/net/packet/play.rs
- pumpkin/src/server/mod.rs
- pumpkin/src/world/mod.rs
Chat "works" but it has a lot of errors and its buggy especially with multiple online players. This PR is meant to more accurately mirror vanilla chat handling logic.
> Various essential chat improvements

- .gitignore
- pumpkin-world/src/chunk/palette.rs
- pumpkin/Cargo.toml
- pumpkin/src/command/commands/mod.rs
- pumpkin/src/command/commands/profile.rs
- pumpkin/src/lib.rs
- pumpkin/src/main.rs
Profile heap usage with `cargo run --features dhat-heap`
> Add memory profiler feature

- pumpkin/src/entity/living.rs
Changed LivingEntity::update_fall_distance so that fall damage works
Verified correct damage in-game.
Issues:
- Water does not stop fall damage
- One time, when I was getting out of water, I took damage. Could not replicate
> Fixed fall damage

- pumpkin/src/entity/mod.rs
Fixes #362 and part 2 of #720 
Could not reproduce the mentioned bugs
> Use latest position for player hitbox

- pumpkin-util/src/lib.rs
- pumpkin-world/src/chunk/palette.rs
Fixes some palettes having possible invalid states
> Harden palette (de)serialization

- pumpkin-config/src/lib.rs
- pumpkin-config/src/whitelist.rs
- pumpkin/src/command/commands/mod.rs
- pumpkin/src/command/commands/whitelist.rs
- pumpkin/src/data/mod.rs
- pumpkin/src/data/op_data.rs
- pumpkin/src/data/whitelist_data.rs
- pumpkin/src/entity/player.rs
- pumpkin/src/net/mod.rs
- pumpkin/src/net/packet/config.rs
- pumpkin/src/server/mod.rs
This PR adds `/whitelist` and everything that it needs to work, as well as `white-list` & `enforce_whitelist` configurations
Player states tested; whitelisted; operator
`enforce_whitelist` has also been tested
Join server with whitelist on/off
Testing `/whitelist on`, `/whitelist off` while both online and in console
Testing output of `/whitelist add`, `/whitelist remove`, `/whitelist reload` `/whitelist list`
> Add whitelist feature

- pumpkin/src/entity/living.rs
This pull request fix the issue #752.
As the title explain the fall damage is ignored when in water
> Fix fall damage when in water

- pumpkin/src/block/blocks/redstone/rails/common.rs
> Fix spelling lint

- pumpkin/src/block/blocks/mod.rs
- pumpkin/src/block/blocks/stairs.rs
- pumpkin/src/block/mod.rs
Adds full placement functionality for all stairs. Handles linking, placement rotation, upside down placement and reshape in neighbor update.
Manual placement of stairs
> Fully fonctionnal stairs

- pumpkin/src/block/blocks/dirt_path.rs
- pumpkin/src/block/blocks/doors.rs
- pumpkin/src/block/blocks/farmland.rs
- pumpkin/src/block/blocks/fence_gates.rs
- pumpkin/src/block/blocks/fences.rs
- pumpkin/src/block/blocks/logs.rs
- pumpkin/src/block/blocks/mod.rs
- pumpkin/src/block/blocks/redstone/buttons.rs
- pumpkin/src/block/blocks/redstone/lever.rs
- pumpkin/src/block/blocks/redstone/observer.rs
- pumpkin/src/block/blocks/redstone/piston.rs
- pumpkin/src/block/blocks/redstone/rails/activator_rail.rs
- pumpkin/src/block/blocks/redstone/rails/detector_rail.rs
- pumpkin/src/block/blocks/redstone/rails/powered_rail.rs
- pumpkin/src/block/blocks/redstone/rails/rail.rs
- pumpkin/src/block/blocks/redstone/redstone_lamp.rs
- pumpkin/src/block/blocks/redstone/redstone_torch.rs
- pumpkin/src/block/blocks/redstone/redstone_wire.rs
- pumpkin/src/block/blocks/redstone/repeater.rs
- pumpkin/src/block/blocks/signs.rs
- pumpkin/src/block/blocks/slabs.rs
- pumpkin/src/block/blocks/stairs.rs
- pumpkin/src/block/blocks/torches.rs
- pumpkin/src/block/mod.rs
- pumpkin/src/block/pumpkin_block.rs
- pumpkin/src/block/pumpkin_fluid.rs
- pumpkin/src/block/registry.rs
- pumpkin/src/net/packet/play.rs
- pumpkin/src/world/mod.rs
Added full slab support, with proper placing, double slab and break loot.
Manual.
> Full slabs support

- pumpkin-data/build/entity_pose.rs
- pumpkin/src/block/blocks/chest.rs
- pumpkin/src/block/blocks/fences.rs
- pumpkin/src/block/blocks/redstone/rails/activator_rail.rs
- pumpkin/src/block/blocks/redstone/rails/detector_rail.rs
- pumpkin/src/block/blocks/redstone/rails/mod.rs
- pumpkin/src/block/blocks/redstone/rails/powered_rail.rs
- pumpkin/src/block/blocks/redstone/rails/rail.rs
- pumpkin/src/block/blocks/signs.rs
- pumpkin/src/block/blocks/stairs.rs
This PR adds:
- Full chest placement (even with crouch)
- Waterlogging on all the already implemented blocks that support it
- Fixed incorrect timing on sugar cane and cactus breaking
Manual
> Chests placement and more waterlogging

- pumpkin/src/entity/hunger.rs
- pumpkin/src/entity/player.rs
The previous implementation was not accurate to vanilla. Some data like difficulty was not being used and some logic branches were missing. 
It's the same as in vanilla, but I manually tested and it feels more like vanilla when testing with normal and peaceful difficulties.
> Fixed hunger depletion and hunger health regen

- pumpkin/src/entity/effect/mod.rs
- pumpkin/src/entity/living.rs
- pumpkin/src/world/mod.rs
Fixes #779 
Effects are now ticking for every living entity. The duration gets counted down and once it reaches zero the effect gets removed and the client gets informed.
I just tested it manually since I didn't find any unit tests for this part of the code. 
> Effects time out

- pumpkin-data/build/block.rs
- pumpkin-world/src/block/mod.rs
- pumpkin/src/block/blocks/chest.rs
- pumpkin/src/block/blocks/fences.rs
- pumpkin/src/block/blocks/glass_panes.rs
- pumpkin/src/block/blocks/iron_bars.rs
- pumpkin/src/block/blocks/mod.rs
- pumpkin/src/block/blocks/redstone/mod.rs
- pumpkin/src/block/blocks/redstone/rails/common.rs
- pumpkin/src/block/blocks/redstone/rails/mod.rs
- pumpkin/src/block/blocks/redstone/repeater.rs
- pumpkin/src/block/blocks/stairs.rs
- pumpkin/src/block/blocks/walls.rs
- pumpkin/src/block/mod.rs
Adds correct placement for glass panes, iron bars, fences (fix) and walls. 
The walls aren't 100% feature complete, as they don't account for things like lanterns place on top of them.
Manual.
> Correct placement for glass panes, iron bars and walls

- pumpkin/src/command/commands/particle.rs
- pumpkin/src/command/commands/setblock.rs
- pumpkin/src/command/commands/summon.rs
- pumpkin/src/command/commands/weather.rs
- pumpkin/src/world/portal/mod.rs
- added more console support for some commands
- refactored `summon.rs` command because of repeating code
- fixed a rare `attempt to subtract with overflow` error related to portal
tested, works fine
> Add more console support for some commands

- pumpkin-world/src/generation/feature/placed_features.rs
This makes trees happy. However, this PR panics on start because of a feature wanting to be placed over the build limit.
You can test trees by adding this code at the start of `PlacedFeature::generate` in `pumpkin-world/src/generation/feature/placed_features.rs`:
```rust
if feature_name != "trees_plains" {
return false;
}
```
> Fixed biome placement modifier

- pumpkin/src/plugin/loader/native.rs
wasm is fine, wasm is cool
no need to put this thing back
> removed removal of wasm annotation

- pumpkin/src/block/blocks/nether_portal.rs
Added delay time to enter the nether based on entity type and gamemode.
in-game test, in creative mode you can enter the nether without any delay (0 tick)
> Add Nether Entry Delay Based on Entity Type and Gamemode

- pumpkin-world/src/chunk/mod.rs
> reintroduce the fix

- pumpkin-util/src/difficulty.rs
- pumpkin-util/src/lib.rs
- pumpkin/src/command/args/difficulty.rs
- pumpkin/src/command/args/mod.rs
- pumpkin/src/command/commands/difficulty.rs
- pumpkin/src/command/commands/mod.rs
- pumpkin/src/command/commands/particle.rs
- pumpkin/src/command/commands/summon.rs
- pumpkin/src/entity/hunger.rs
- pumpkin/src/entity/player.rs
- pumpkin/src/server/mod.rs
- pumpkin/src/world/mod.rs
Implement /difficulty <difficulty> command.
Video:
https://github.com/user-attachments/assets/e22c3d90-1250-4dd7-9459-0f6e6d9c3091
> Implement /difficulty command

- Cargo.toml
- pumpkin-protocol/src/ser/deserializer.rs
- pumpkin-protocol/src/ser/mod.rs
- pumpkin-protocol/src/ser/serializer.rs
Implemented todos and unimplemented (de)serialization in `pumpkin-protocol/src/ser/serializer.rs` and `pumpkin-protocol/src/ser/deserializer.rs`
Added tests in the `pumpkin-protocol/src/ser/mod.rs`
> Implement Missing (De)Serializations

- pumpkin/src/block/blocks/fence_gates.rs
the gate's facing should be changed to opposite direction when player open it on the opposite side
fix fence gate's facing when open
> fix fence gate's facing when open

- Cargo.lock
- Cargo.toml
- pumpkin-api-macros/Cargo.toml
- pumpkin-api-macros/src/lib.rs
- pumpkin-macros/Cargo.toml
- pumpkin-macros/src/lib.rs
Make proc macro errors actual errors and not just panics.
It shouldn't break anything but this definitely needs a code review.
> Improve errors from proc macros

- pumpkin/src/block/blocks/carpet.rs
- pumpkin/src/block/blocks/mod.rs
- pumpkin/src/block/mod.rs
Implement carpet (placeing and breaking)
Place a carpet (you can't place it if there is no block under)
Break a carpet (if one is on top, he break too)
> Implement Carpet

- pumpkin/src/block/blocks/redstone/copper_bulb.rs
- pumpkin/src/block/blocks/redstone/mod.rs
- pumpkin/src/block/mod.rs
> add CopperBulbBlock

- pumpkin/src/block/blocks/trapdoor.rs
Fix the issue where other players can't hear the sound of the trapdoor.
familiar with #926
tested in game
> Resolve missing trapdoor sound for other players

- pumpkin-data/build/recipes.rs
Added basic deserialization for CookingRecipe from recipes.json
> Recipes: add cooking recipes

- pumpkin/src/item/items/mace.rs
- pumpkin/src/item/items/mod.rs
- pumpkin/src/item/items/no_creative_mining_item.rs
- pumpkin/src/item/items/swords.rs
> Add Mace and Trident to no creative mining item

- pumpkin/src/entity/experience_orb.rs
- pumpkin/src/entity/hunger.rs
- pumpkin/src/entity/item.rs
- pumpkin/src/entity/player.rs
- pumpkin/src/world/mod.rs
> Drop items & xp and reset hunger on death

- pumpkin-protocol/src/bedrock/client/raknet/unconnected_pong.rs
- pumpkin-protocol/src/bedrock/packet_decoder.rs
- pumpkin-protocol/src/bedrock/packet_encoder.rs
- pumpkin-protocol/src/bedrock/server/raknet/unconnected_ping.rs
- pumpkin/src/net/bedrock/login.rs
- pumpkin/src/net/bedrock/mod.rs
- pumpkin/src/net/bedrock/unconnected.rs
Now we get the serder error TooLarge("string") because the login packets are just a few very large strings
> Fixed missing ACKs

- Cargo.lock
- pumpkin-data/Cargo.toml
- pumpkin-data/build/build.rs
> Add rayon to data build.rs

- .gitignore
This is useful when testing world loading with vanilla minecraft or Paper.
> Add Paper and Vanilla to .gitignore

- pumpkin-data/build/fluid.rs
- pumpkin-data/build/item.rs
- pumpkin-data/build/tag.rs
- pumpkin-data/src/blocks.rs
- pumpkin-world/src/block/entities/dropper.rs
- pumpkin/src/block/blocks/piston/piston_extension.rs
- pumpkin/src/block/blocks/piston/piston_head.rs
- pumpkin/src/block/registry.rs
- pumpkin/src/item/registry.rs
optimize BlockRegistry and several small change
before
```
get_pumpkin_block       time:   [52.939 ns 53.738 ns 54.587 ns]
change: [+569.28% +587.62% +602.61%] (p = 0.00 < 0.05)
Performance has regressed.
Found 14 outliers among 100 measurements (14.00%)
2 (2.00%) high mild
12 (12.00%) high severe
```
after
```
Running benches\bench_block.rs (target\release\deps\bench_block-c1fa4b06525777e2.exe)
Gnuplot not found, using plotters backend
get_pumpkin_block       time:   [7.5270 ns 7.5767 ns 7.6414 ns]
change: [−4.8425% −2.5811% −0.0623%] (p = 0.05 < 0.05)
Change within noise threshold.
Found 8 outliers among 100 measurements (8.00%)
1 (1.00%) low mild
2 (2.00%) high mild
5 (5.00%) high severe
```
i also tried other optimizations, but failed.
apply simd to aquifer_sampler.rs, but it runs a …
> Change BlockRegistry and ItemRegistry  to use u16

- README.md
Fix the quick start link in readme
Not need
> docs: fix quick start link

- pumpkin-util/src/math/experience.rs
- pumpkin/src/command/commands/experience.rs
https://minecraft.wiki/w/Experience
Should have been done by #521 
> Fix the XP Calculations

- pumpkin-world/src/chunk/mod.rs
Should fix #675. From my testing, it is now vanilla compliant.
manual
> Fix water disappearance discrepancies

- pumpkin-data/build/damage_type.rs
- pumpkin/src/block/blocks/nether_portal.rs
- pumpkin/src/entity/living.rs
- pumpkin/src/entity/mod.rs
- pumpkin/src/entity/player.rs
- pumpkin/src/item/registry.rs
- pumpkin/src/world/mod.rs
Fix damage sound & death message display.
Fall into void.
> Fix damage & death msg & portal delay

- .github/workflows/docker.yml
- .github/workflows/rust.yml
- .github/workflows/typos.yml
- pumpkin-registry/src/lib.rs
- pumpkin-util/src/lib.rs
- pumpkin-world/src/generation/feature/configured_features.rs
- pumpkin-world/src/generation/feature/placed_features.rs
- pumpkin-world/src/generation/settings.rs
- pumpkin-world/src/generation/structure/mod.rs
Resolves #1123
Abstract changes in 8c859953ee4d10927b2ba1e5fc27a95cd9fd58b8 to `include_json_static` macro.
> fix: use static files by include_json_static (#1123)

- pumpkin-inventory/src/player/player_screen_handler.rs
- pumpkin-inventory/src/screen_handler.rs
- pumpkin-protocol/src/java/client/play/set_equipment.rs
- pumpkin/src/entity/player.rs
- pumpkin/src/net/java/play.rs
- pumpkin/src/server/mod.rs
- pumpkin/src/world/mod.rs
This PR fixes the bug described in issue #1142 where player tasks could not be completed, and implements the player's ability to equip armor.
https://github.com/user-attachments/assets/7b64ca54-86a0-4c3f-b013-2c0028666d05
> Implement equipping armor and resolve difficulty deadlock

- pumpkin/src/entity/ai/control/look_control.rs
- pumpkin/src/entity/ai/goal/active_target_goal.rs
- pumpkin/src/entity/ai/goal/ambient_stand_goal.rs
- pumpkin/src/entity/ai/goal/goal_selector.rs
- pumpkin/src/entity/ai/goal/look_around_goal.rs
- pumpkin/src/entity/ai/goal/look_at_entity.rs
- pumpkin/src/entity/ai/goal/melee_attack_goal.rs
- pumpkin/src/entity/ai/goal/mod.rs
- pumpkin/src/entity/ai/goal/move_to_target_pos_goal.rs
- pumpkin/src/entity/ai/goal/step_and_destroy_block_goal.rs
- pumpkin/src/entity/ai/goal/track_target_goal.rs
- pumpkin/src/entity/ai/goal/zombie_attack_goal.rs
- pumpkin/src/entity/ai/target_predicate.rs
- pumpkin/src/entity/mob/mod.rs
- pumpkin/src/entity/mob/zombie.rs
- pumpkin/src/entity/mod.rs
Fixed zombie head vibrations.
Made the entire system 999% faster and human readable again ;).
Transformed a good amount of dyn code into generics.
> Goal system rework (life saving)!
